### ISSUE TITLE
Bug: Better aligment of new releases for client and server

### ISSUE THREAD

**Issue by hillbicks** [TomBursch/kitchenowl#115]
### Is this urgent?

No

### What parts are affected

Both

### What are the Server/Client versions of KitchenOwl

0.3.10/0.3.6

### What's the problem 🤔

Hey there,

currently the fdroid repo is still on version 0.3.6, while google play and the server are already on 0.3.10. 

It would be great if these releases could be aligned so that all versions are published at the same time. This was probably the "worst" case scenario and my fault as well. watchtower updated the server version while I was shopping and then kitchenowl was not usable anymore, since the client version is still on 0.3.6. 

Maybe you could release the server update automatically once the versions on fdroid and google play were published?

Thanks for looking into this! 

### Share your logs

```log
I don't think it is needed.
```

### Share your configuration

```yml
I don't think it is needed.
```

**Comment by TomBursch** [comment]
Hey, 
Yeah sorry about that. I don't think there will be any breaking change anytime soon. I usually try to keep at least the latest two app versions supported by the backend. 
F-droid takes usually a bit longer than the rest. You could also download the APK directly from github and update it that way for now. https://github.com/TomBursch/kitchenowl/releases/tag/v0.3.10

**Comment by hillbicks** [comment]
No worries! Like I said, I'm to blame for updating automatically, I just though I'd let you (and others) know about this as well. 

I'll wait until fdroid is published though, I already went shopping today. :grin: 

We can close this issue if you want.
