### ISSUE TITLE
Feature request: Allow fixing typo after adding item to shopping list

### ISSUE THREAD

**Issue by tincanman21** [TomBursch/kitchenowl#121]
### What's the feature 🧐

Is there a way to be able to fix a typo after adding an item to the shopping list? If not would it be possible to add this feature?
The only way I can see to fix a typo is to delete and readd.

**Comment by TomBursch** [comment]
There currently isn't. Not sure what would be the best way to handle this. Unless there are many people having an issue with this I don't think I'll add a solution to this minor problem.

**Comment by Kuebic** [comment]
There totally are many people having issues with this, even if they don't say it here. Typos happen, and sub-par imports happen. And by not having the ability to do so easily leads to messy shopping lists and is a pain to clean.

What would totally help is be able to easily change an ingredient's to one that already exists and keep the description without deleting and re-adding and/or have a better ingredient auto-detect system when importing recipes.

For ingredients to be grouped together in the shopping list, they have to match exactly. Having `brown sugar` `Brown sugar` `Brown Sugar` `sugar, brown` `Sugar, brown` will have them all as separate items and makes the shopping list less usable. Being able to easily fix this without going to the recipe, add new ingredient, copy description over, delete old one would save a lot of time.

![image](https://github.com/TomBursch/kitchenowl/assets/10050997/6a2faa8a-3ffe-4660-8288-a0c1955d4088)

![image](https://github.com/TomBursch/kitchenowl/assets/10050997/a7857e3e-b306-4ee7-9ef8-99639dc79f56)


Anytime I import recipes, 99% of the time I have to re-add each ingredient so they can take advantage of clustering, auto-categorization and icons, and manually match previously entered ingredients, almost defeating the purpose of importing to save time. Anything to make organizing ingredients easier is a MAJOR quality-of-life improvement.

My suggestion is to focus on being able to easily change an ingredient to one that already exists. So if I long-press an item in the shopping list (where it's most apparent), one of the options in the dropdown menu should be "change to" that give a list of similar default ingredients and previously entered ingredients.
