### ISSUE TITLE
Feature request: More recent items

### ISSUE THREAD

**Issue by xEtarusx** [TomBursch/kitchenowl#125]
### What's the feature 🧐

Hey there,
currently the "Recent Items" list displays 9 items and I would love to see more of my recent items. A comparison would be the Bring! app which shows 24 recent items.
Or maybe make it a configurable amount in the settings (if that's a better way of handling it).

Thanks and regards
Etarus

**Comment by kebbe** [comment]
Having the complete recent items list there, even with the category structure would be awesome. 
Most of the time we are buying the same stuff again and it's much more comfortable to go through a list to check what is missing / needed.

Thank you for this great project!
