### ISSUE TITLE
Feature request: Add support for any url prefix / subdirectory

### ISSUE THREAD

**Issue by schinivision** [TomBursch/kitchenowl#130]
### What's the feature 🧐

As stated in the documentation the ```front_url``` environment variable is ignored. This feature leaves out the option to pass any information to the front end that it is served under a different URL/path. Therfore requests will fail.

Usually this is not so much of an issue if hosted on a subdomain because it can be ignored, or hosted on root path and this will be the default behaviour of the application.

But this leaves out the possiblity for people to host this applicaiton when they have dyndns or other limitations where it is not possible to host it on a different subdomain and hosting has to be done via subdirectories.

**Comment by TomBursch** [comment]
Just FYI until this is implemented. You should be able to use the mobile/dedicated app just fine. It's only the web app that has a problem with this.

**Comment by pedroapero** [comment]
> Just FYI until this is implemented. You should be able to use the mobile/dedicated app just fine. It's only the web app that has a problem with this.

Hello, can you give more details? I thought the app was necessarily going through the webUI.

**Comment by schinivision** [comment]
This is awesome. Thanks @TomBursch for adding this. Eagerly waiting for the new release.

**Comment by TomBursch** [comment]
All credits go to @JVMerkle 😄
I'll publish a new version next week :)
