### ISSUE TITLE
Feature request: Provide F-Droid package

### ISSUE THREAD

**Issue by irishrain** [TomBursch/kitchenowl#14]
### What's the feature 🧐

There is probably some overlap between "people who want a self hosted FOSS solution for their shopping list" and "people who prefer not to use the play store"

**Comment by ALutz273** [comment]
Hello, 

I have found this tutorial.  -> https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/
But I would make the Android app into its own repo as the first.

**Comment by TomBursch** [comment]
Thanks @ALutz273 for the great tutorial!
Sorry it took so long but there were many other issues/features that had higher priority.
I will close this issue when the app is available (you can follow the progress here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11771)
