### ISSUE TITLE
Bug (Web): Autofill does not work

### ISSUE THREAD

**Issue by kinslayer1982** [TomBursch/kitchenowl#142]
Hi,

i'm trying to get bitwarden to autofill my kitchenowl login, but it's not working. Bitwarden cannot identify the username/password fields and i haven't been able to get it working. As far as i can tell looking at the html code of the login page the ids should be "username" and "current-password". 
Never had an issue with bitwarden not being able to detect input fields before.

**Comment by TomBursch** [comment]
I think this is an issue with flutter web itself (https://github.com/flutter/flutter/issues/61301).

**Comment by TomBursch** [comment]
Fixed with the latest version.
