### ISSUE TITLE
Bug: Dockerifle healthcheck interval too high

### ISSUE THREAD

**Issue by b5l** [TomBursch/kitchenowl#144]
### Is this urgent?

No

### What parts are affected

Frontend

### What are the Server/Client versions of KitchenOwl

"latest" tag on docker hub (image id: 91f4465744c6)

### What's the problem 🤔

I'm currently trying to run kitchenowl with traefik. Traefik detects newly started containers and, based on labels, routes traffic to them. However, it only picks them up after docker considers them healthy.

The current healthcheck interval of 5 minutes in the Dockerfile leads to the service being unavailable through traefik for 5 full minutes of being actually healthy.

I think the same issue is probably the case for any tool inspecting running containers. The health check interval should be a lot smaller, since nginx doesn't actually need 5 minutes for starting up.

**Comment by TomBursch** [comment]
I agree that 5 minutes is a bit high, I'll think about reducing it to 60s. The problem is not really that nginx takes that long to start, but more so that every health check causes a database lookup (although this will be removed in the next release) and anything shorter might waste resources on less powerful systems.

Just FYI, you can manually override the interval length https://docs.docker.com/engine/reference/run/#healthcheck

**Comment by b5l** [comment]
I'm unsure if it's a good practice to have the frontend's health check be tied to the backend in such a way. This way, even if there are only issues with the backend service, it's frontend that seems unhealthy on first glance.

Instead, I'd suggest implementing independent health checks for both services. The backend service could be checked every 1 minute or so using the same check that also triggers the DB call, and the frontend service could be checked more frequently using a less resource-intensive check, like testing whether `HEAD /` returns a 2xx/3xx status.

Since frontend depends on the backend image, it will still not be considered healthy (or even started) by docker compose until the backend health check comes back successful.

And thanks for the docker docs reference, I was actually missing that! :)
