### ISSUE TITLE
Feature request: Adding amount and unit property to groceries.

### ISSUE THREAD

**Issue by FilipeRamalho** [TomBursch/kitchenowl#152]
## What's the feature 🧐

Currently, to set an amount, you have to add the property "500g" to an item, for example.

However, if you start to add items from several recipes together, you will get descriptions such as "500 g, 300 g". 

This is fine and even has some advantages, but I think we can have the best of both worlds.

By adding the two properties "Unit" and "Amount" you can add features like
- Every time you add an item from a recipe, it just increases the amount field, so you automatically have the total amount needed in the grocery overview.
- You can add a plus and minus icon or number field for each grocery to increase the amount property, which is a bit easier than changing the description field (here an additional increase amount property might be useful if a plus icon is used).

Now this would obviously clash with the current description field, and it would also break some existing installations **unless** some sort of porting is implemented.

## Conflicts with description field

Assuming we've successfully ported the description field so that it's not used to track the amount of food, there are still a few problems.

- For example, what if we have the items "Cookies - Desc: Leibniz" and "Cookies - Desc: Milka"? 

As it is now, it would appear as 
<img width="97" alt="image" src="https://user-images.githubusercontent.com/25137217/233638395-d48485ae-f352-4c84-a872-195e05ebf7d8.png">

If we now add amounts, we would either need two separate icons or we would have to display the text differently. (something like a unique description: amount unit, ...)

I can see several problems with the second solution (text length, complicated logic to add, ...), so it seems better to separate the items by their description. 

## Backwards compatibility

The description field is currently already used for tracking amounts, so this solution would have to port that (especially considering the conflicts with the description field).

I think this would require some complicated logic, and it would also be limited because it's impossible to account for every type of unit used. (Because any kind of logic like this would have to look for specific units).

So for now, it would be best not to do it automatically (so the admin has to trigger it) and only include the migration algorithm for a few releases to avoid future bloat.

But even with all that, it's definitely doable and pretty easy for most cases (the edge cases are what would complicate this)

For example, description fields with just a number can be converted to "Amount: Number, Unit: Piece/s". And if it's a list of numbers, then they get added up. Things like "50ml, 60ml" can also be easily converted if the unit is known.

This would cover most of the current uses.

For the rest, the admin can get feedback on how many items need manual approval.

**Comment by TomBursch** [comment]
Thanks for the detailed feature request! 
First, let me say that merging descriptions should work, are you running the latest backend version? See #100 for more information and the discussion we had about that. It detects SI units and merges them correctly.

Although the dynamic merging has some flaws sometimes, I still prefer this over adding units and amounts. Managing units is a bit annoying and not something I would want the user to do (I didn't like that about grocy). Adding buttons to increase the amount would also work with the current system, we don't need units/amounts for that.

**Comment by FilipeRamalho** [comment]
I actually did miss that!

That does clear most of the stuff I mentioned. I'll try it out, thx.
