### ISSUE TITLE
Bug: unable to Change or add accounts

### ISSUE THREAD

**Issue by vincemue** [TomBursch/kitchenowl#157]
### Is this urgent?

Yes

### What parts are affected

Frontend

### What are the Server/Client versions of KitchenOwl

0.4.3

### What's the problem 🤔

After updating I am not able to change existing accounts or ad new accounts. I can only find the Option to add members to a household.

**Comment by TomBursch** [comment]
The option is still there, it can be found under server → users. See below in the screenshot:
![github](https://github.com/TomBursch/kitchenowl/assets/9092682/cc53b609-5360-4847-89b4-dcc19223faad)

**Comment by vincemue** [comment]
I found the member section, but am only able to add a member to the
household.

The User section ist Not available for me.

I was Admin before the Update and still was Admin in the household.

Am I Missing anything?

Tom Bursch ***@***.***> schrieb am Do., 11. Mai 2023, 15:59:

**Comment by TomBursch** [comment]
There is a difference now between a household and server admin. With the migration, only the "owner" (the first user on the server)  was promoted to server admin, not all household admins. Your other user should be able to make you a server admin.

**Comment by vincemue** [comment]
I am the First User on the Server and only added my wife Afterwards. Is there an other way to promote myself to Server Admin again?
@TomBursch

**Comment by TomBursch** [comment]
Update your server to the latest version and run the following command:
`docker exec -it NAME_OF_THE_BACKEND_CONTAINER python manage.py`
The rest should be self-explanatory, it is an interactive script that lets you manage your server and make yourself an admin again. 
Just to make sure that there is no greater issue here, could you tell me if there was really no other admin present or if another account became the admin.

**Comment by vincemue** [comment]
Thanks for the Response. I will try it later. I assume I need to run the command in the Backend Container console? I am running it in unraid. 

I checked the Database and assume its the following table:
![Screenshot_20230512-195838_SQLite Editor](https://github.com/TomBursch/kitchenowl/assets/120366587/8486333a-f14a-414d-9a28-87a88a30487f)

**Comment by TomBursch** [comment]
Inside the container you can just run `python manage.py`. 

Thanks for the screenshot, another solution would've been to just set the admin value to 1. 
Strange that no one gained admin rights, will have to do some digging.

**Comment by vincemue** [comment]
> Inside the container you can just run `python manage.py`.
> 
> Thanks for the screenshot, another solution would've been to just set the admin value to 1. Strange that no one gained admin rights, will have to do some digging.

Thanks, the Script worked and I am Admin again.
How ist the Initial owner defined? By earliest creation Date?

**Comment by TomBursch** [comment]
There were two boolean flags on the user admin and owner, the user created during onboarding had owner set to true. Those were both migrated to the household membership settings and a new field server_admin was added to the user with the same value as owner. I think there is definitely a bug in the migration since multiple people had the same issue. Will look into this and reopen the issue.

**Comment by TomBursch** [comment]
There was indeed an issue in the migration script, which is fixed now. This should also fix this issue for existing instances, by making the user with the lowest ID admin if no admin is present on the server.
