### ISSUE TITLE
Feature request: Add item with description from search

### ISSUE THREAD

**Issue by AndreKR** [TomBursch/kitchenowl#168]
I'm trying to add an item to the shopping list together with a _description_ (the smaller, lighter colored text).

One way to do that is to type the item name, a comma and then the description, but as far as I know that requires typing out the entire item name (making the search useless).

So what I tried instead:
* I type part of the item name.
* I wait for the appropriate tile to show up.
* I hold the tile.
* The screen with the description input appears.
* I enter the description.
* I press the back arrow in the top left corner.

I'm now back at the search. This kind of makes sense, but if I hold a tile that is already in the shopping list, I get to the exact same screen, where I can edit the description and then the back arrow saves it. So I would somewhat expect it to work the same when coming from the search screen.

**Comment by TomBursch** [comment]
You don't need to enter the full name when searching for an item and adding a description using a comma. The search returns the same items whether or not you've added a description to your search.


About your second method, you're right that should be possible and is a bug.

**Comment by AndreKR** [comment]
Thanks for the fix, I have used this flow now for a while and there's one thing that's still bothering me. When I type something into the search, then hold the tile to add a description, enter a description and then click the back arrow, I feel like the search should be cleared. What do you think?

**Comment by TomBursch** [comment]
@AndreKR I've updated the behavior, it will be available in the next release.
