### ISSUE TITLE
Bug:  invalid request block size: 21573 (max 4096)...skip

### ISSUE THREAD

**Issue by TobiasLeuschner** [TomBursch/kitchenowl#17]

**Comment by Thoroslives** [comment]
I am getting this issue, just tried setting this up
![image](https://user-images.githubusercontent.com/78023877/167982611-b7927b87-a44b-491c-b4e4-89c262fbc9b8.png)

**Comment by TomBursch** [comment]
I guess you're using the unraid app store version as well? I've never used unraid nor setup the community plugin, so if anyone could provide information on how to change the configuration there that would be great. This bug occurs when the wrong port is exposed of the container. See https://tombursch.github.io/kitchenowl/get-started/ for the configuration. Either the backend or the frontend open up port 80. What happens here is that the backend's port 5000 is used which, starting from v0.0.33, is only used internally.

**Comment by Thoroslives** [comment]
Okay I've done so now having the container port set to 80 and the host port to 5000 its working, thanks a bunch :)
