### ISSUE TITLE
Feature request: Ingredient pills with quantity

### ISSUE THREAD

**Issue by Ombrelin** [TomBursch/kitchenowl#202]
### What's the feature 🧐

Something which I've always found frustrating on recipe either in books / website / apps is that when reading, you always need to go back and forth between the recipe instructions and the ingredients to see the ingredient quantity. It would be nice to have a way to reference the ingredient (maybe something similar to when we reference github issues in text with the # ?) so that when it is rendered, there is a little pill saying the name AND quantity, so that it reads fluently.

**Comment by TomBursch** [comment]
Damn, this is such a good idea, love it. Especially if this scales with selected yields.

**Comment by TomBursch** [comment]
There are still some alignment issues that need resolving, but all in all, I'm pretty happy with it already:
![image](https://github.com/TomBursch/kitchenowl/assets/9092682/6f75d9bf-e61f-4517-9d75-62ea3976f8d7)


Some of which are cause by https://github.com/flutter/flutter/issues/123195

**Comment by Ombrelin** [comment]
Big up to you for doing it so quickly !!
It is really good looking already 👍

**Comment by Ombrelin** [comment]
Hi @TomBursch,
I've pulled the dev version to try the new feature ; what is the syntax you chose for referencing an ingredient ?
I tried reading the PR to figure out, but I'm not very well versed in Dart :'(

**Comment by TomBursch** [comment]
Hey, no problem, the syntax is `@item_name`. It's case-insensitive and uses underscores for spaces.
