### ISSUE TITLE
Bug: Auto import not working from coco

### ISSUE THREAD

**Issue by diminou91** [TomBursch/kitchenowl#204]
### Is this urgent?

None

### What parts are affected

Frontend

### What are the Server/Client versions of KitchenOwl

77/74

### What's the problem 🤔

Hi there, thank you very much for this really helpful service !

When trying to auto import a recipe from coco, it's just not working. Nothing really helpful seems to happen in the logs, but I'll share them if needed.

Example of faulty URL : https://www.coco.cooking/recette/Bruschetta-de-champignons

Thank in advance for your time!

**Comment by TomBursch** [comment]
It seems coco.cooking is not supported by [recipe-scrapers](https://github.com/hhursev/recipe-scrapers). You will have to open an issue/request there.
