### ISSUE TITLE
Bug: Can create new users, but cannot make a Household

### ISSUE THREAD

**Issue by sadsephiroth** [TomBursch/kitchenowl#215]
### Is this urgent?

None

### What parts are affected

Frontend

### What are the Server/Client versions of KitchenOwl

tombursch/kitchenowl:latest / tombursch/kitchenowl-web:latest

### What's the problem 🤔

I cannot make a household, the "add" button stays greyed out. I can access via local, web, and through app no problems. Created myself and added wife as user, when going to create a household, no matter what I do the add button cannot be selected. I am running in Docker, have tried compose and creating manually through Portainer. I have a bind mount for the data directory, and have confirmed permissions are correct. There is a data base file and an upload folder that was created at containter startup.

### Share your logs

```log
172.18.0.1 - - [05/Aug/2023:18:16:56 +0000] "POST /api/auth HTTP/1.1" 200 563 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:16:56 +0000] "GET /api/user HTTP/1.1" 200 1203 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:16:57 +0000] "GET /api/household HTTP/1.1" 200 3 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:16:59 +0000] "GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V/supported-languages HTTP/1.1" 200 437 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:17:03 +0000] "GET /api/user/search?query=M HTTP/1.1" 200 261 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:17:04 +0000] "GET /api/user/search?query=Mon HTTP/1.1" 200 132 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
127.0.0.1 - - [05/Aug/2023:18:17:13 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:17:43 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:18:13 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:18:43 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:19:13 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:19:43 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:20:13 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
172.18.0.1 - - [05/Aug/2023:18:20:21 +0000] "GET /api/household HTTP/1.1" 200 3 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:20:21 +0000] "GET /api/household HTTP/1.1" 200 3 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:20:21 +0000] "GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V/supported-languages HTTP/1.1" 200 437 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:20:24 +0000] "GET /api/user/search?query=M HTTP/1.1" 200 261 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:20:25 +0000] "GET /api/user/search?query=Mo HTTP/1.1" 200 132 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
127.0.0.1 - - [05/Aug/2023:18:20:43 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:21:13 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:21:44 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:22:14 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:22:44 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:23:14 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:23:44 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:24:14 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:24:44 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:25:14 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:25:44 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
127.0.0.1 - - [05/Aug/2023:18:26:14 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"


[pid: 42|app: 0|req: 8/8] 172.18.0.1 () {52 vars in 1026 bytes} [Sat Aug  5 18:17:04 2023] GET /api/user/search?query=Mon => generated 132 bytes in 15 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 9/9] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:17:29 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 10/10] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:18:29 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 11/11] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:19:29 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 12/12] 172.18.0.1 () {52 vars in 1003 bytes} [Sat Aug  5 18:20:21 2023] GET /api/household => generated 3 bytes in 19 msecs (HTTP/1.1 200) 2 headers in 70 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 13/13] 172.18.0.1 () {52 vars in 1003 bytes} [Sat Aug  5 18:20:21 2023] GET /api/household => generated 3 bytes in 29 msecs (HTTP/1.1 200) 2 headers in 70 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 14/14] 172.18.0.1 () {52 vars in 1103 bytes} [Sat Aug  5 18:20:21 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V/supported-languages => generated 437 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 15/15] 172.18.0.1 () {52 vars in 1022 bytes} [Sat Aug  5 18:20:24 2023] GET /api/user/search?query=M => generated 261 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 16/16] 172.18.0.1 () {52 vars in 1024 bytes} [Sat Aug  5 18:20:25 2023] GET /api/user/search?query=Mo => generated 132 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 17/17] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:20:29 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 18/18] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:21:29 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 19/19] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:22:29 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 20/20] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:23:29 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 21/21] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:24:29 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 22/22] 127.0.0.1 () {28 vars in 372 bytes} [Sat Aug  5 18:25:29 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 23/23] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:26:29 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
```

### Share your configuration

```yml
version: "3"
services:
    front:
        image: tombursch/kitchenowl-web:latest
        ports:
        - "4008:80"
        depends_on:
        - back
        networks:
        - default
    back:
        image: tombursch/kitchenowl:latest
        restart: unless-stopped
        networks:
        - default
        environment:
        - JWT_SECRET_KEY=kitchenowl
        volumes:
        - kitchenowl_data:/data

volumes:
    kitchenowl_data:

networks:
    default:
```

**Comment by TomBursch** [comment]
Are those all the logs you have? It's missing the post request where you're trying to create the household, something like `post /api/household` and there should be an error message somewhere. I cannot reproduce this right now, so I'm not sure where the issue might be without those.

**Comment by sadsephiroth** [comment]
172.18.0.1 - - [05/Aug/2023:18:47:43 +0000] "GET /api/household HTTP/1.1" 401 28 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:43 +0000] "GET /api/household HTTP/1.1" 401 28 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:43 +0000] "GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V HTTP/1.1" 200 52 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:43 +0000] "GET /api/auth/refresh HTTP/1.1" 200 563 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:43 +0000] "GET /api/household HTTP/1.1" 200 3 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:43 +0000] "GET /api/household HTTP/1.1" 200 3 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:44 +0000] "GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V/supported-languages HTTP/1.1" 200 437 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:45 +0000] "GET /api/household HTTP/1.1" 200 3 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:45 +0000] "GET /api/household HTTP/1.1" 200 3 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:45 +0000] "GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V/supported-languages HTTP/1.1" 200 437 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:46 +0000] "GET /api/household HTTP/1.1" 200 3 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
172.18.0.1 - - [05/Aug/2023:18:47:46 +0000] "GET /api/household HTTP/1.1" 200 3 "-" "Dart/3.0 (dart:io)" "174.105.80.197"
127.0.0.1 - - [05/Aug/2023:18:47:47 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/8.1.2" "-"
172.18.0.1 - - [05/Aug/2023:18:47:47 +0000] "GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V/supported-languages HTTP/1.1" 200 437 "-" "Dart/3.0 (dart:io)" "174.105.80.197" 

and

[pid: 42|app: 0|req: 43/43] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:46:31 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 44/44] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:47:31 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 45/45] 172.18.0.1 () {52 vars in 1003 bytes} [Sat Aug  5 18:47:43 2023] GET /api/household => generated 28 bytes in 1 msecs (HTTP/1.1 401) 2 headers in 81 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 46/46] 172.18.0.1 () {52 vars in 1003 bytes} [Sat Aug  5 18:47:43 2023] GET /api/household => generated 28 bytes in 0 msecs (HTTP/1.1 401) 2 headers in 81 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 47/47] 172.18.0.1 () {52 vars in 1063 bytes} [Sat Aug  5 18:47:43 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 48/48] 172.18.0.1 () {52 vars in 1011 bytes} [Sat Aug  5 18:47:43 2023] GET /api/auth/refresh => generated 563 bytes in 47 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 49/49] 172.18.0.1 () {52 vars in 1003 bytes} [Sat Aug  5 18:47:43 2023] GET /api/household => generated 3 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 70 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 50/50] 172.18.0.1 () {52 vars in 1003 bytes} [Sat Aug  5 18:47:43 2023] GET /api/household => generated 3 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 70 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 51/51] 172.18.0.1 () {52 vars in 1103 bytes} [Sat Aug  5 18:47:44 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V/supported-languages => generated 437 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 52/52] 172.18.0.1 () {52 vars in 1003 bytes} [Sat Aug  5 18:47:45 2023] GET /api/household => generated 3 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 70 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 53/53] 172.18.0.1 () {52 vars in 1003 bytes} [Sat Aug  5 18:47:45 2023] GET /api/household => generated 3 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 70 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 54/54] 172.18.0.1 () {52 vars in 1103 bytes} [Sat Aug  5 18:47:45 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V/supported-languages => generated 437 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 55/55] 172.18.0.1 () {52 vars in 1003 bytes} [Sat Aug  5 18:47:46 2023] GET /api/household => generated 3 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 70 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 56/56] 172.18.0.1 () {52 vars in 1003 bytes} [Sat Aug  5 18:47:46 2023] GET /api/household => generated 3 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 70 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 57/57] 172.18.0.1 () {52 vars in 1103 bytes} [Sat Aug  5 18:47:47 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V/supported-languages => generated 437 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 42|app: 0|req: 58/58] 127.0.0.1 () {28 vars in 373 bytes} [Sat Aug  5 18:48:31 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)

when clicking add then back a few times.

**Comment by TomBursch** [comment]
Hmm, this still does not include what I'm looking for. Does this happen on the web app or using a dedicated (android/iOS) app?

**Comment by TomBursch** [comment]
Oh, wait, I just reread your description and you said that the add button is not enabled. Did you give the household a name? The button is enabled only if the household name is not empty.

**Comment by sadsephiroth** [comment]
Both. The OP logs are from local web, and the update is the mobile app. With the --details option im not getting anything more than the request.

**Comment by sadsephiroth** [comment]
That was it! Looks like you can't just type a name and click away, you have to hit enter before it is actually accepted, even though what you typed remains in the field. Thank you so much for the quick reply and troubleshooting. Might either recommend making the add button to change to green when it enables, or a button to accept the name to make it more obvious to those of us too dumb to realize lol.

**Comment by TomBursch** [comment]
Great that this was the issue, will overhaul the button behavior a bit 😄 Thanks for the prompt replies!
