### ISSUE TITLE
Wiki issue: Cosmos installer

### ISSUE THREAD

**Issue by azukaar** [TomBursch/kitchenowl#219]
### URL to the Wiki page

*

### What's the issue?

I added a one click installer to Cosmos for KitchenOwl, in case you want to mention it somewhere in the install process for example.
There's also a link that gives you the app on the market directly: https://cosmos-cloud.io/proxy#cosmos-ui/market-listing/cosmos-cloud/KitchenOwl 

Feel free to close this ticket if irrelevant!
Thanks!

![image](https://github.com/TomBursch/kitchenowl/assets/7872597/73101eb1-0cda-479a-81de-4b1f823c1e29)

**Comment by TomBursch** [comment]
Thanks! I've added it to the possible installation methods in the documentation 👍🏼
