### ISSUE TITLE
Bug: List style doesn't highlight items in shopping list

### ISSUE THREAD

**Issue by pizzapim** [TomBursch/kitchenowl#221]
### Is this urgent?

No

### What parts are affected

Frontend

### What are the Server/Client versions of KitchenOwl

backend v75 docker image, android app v0.4.8

### What's the problem 🤔

If I change my setting of Shopping list style to List, the items on my shopping list are no longer highlighted in bright green. This is quite confusing.

![image](https://github.com/TomBursch/kitchenowl/assets/23135512/72f5db5a-4ea8-418e-92f6-05adf25c7eab)
![image](https://github.com/TomBursch/kitchenowl/assets/23135512/7b1d7eb3-ea8f-430a-93e8-400c7a2911d2)

**Comment by TomBursch** [comment]
Hmm yeah I get why it's confusing, but it just looked really weird when I tried it with all of them green/selected. There is also an issue about inconsistency #179. I'll add it to my list to redo/rethink. I hope I'll have time for that and this issue next month.

**Comment by pizzapim** [comment]
Thanks. I also showed this app to my mother, and she was a bit confused about the shopping list page as well. When you have ticked off every item, you are left with only gray items but she thought they were all on the list still. Maybe making the text grayed-out as well makes it more clear they are not currently on the list.
