### ISSUE TITLE
Feature request: One-Click-Solution for balancing payments (expenses section)

### ISSUE THREAD

**Issue by SimSon2710** [TomBursch/kitchenowl#226]
### What's the feature 🧐

It would be useful to have an extra button (or some other simple way) in the expenses section to

1. get recommendations for optimal balancing payments (that is, who should pay how much to whom),
2. make the payments by entering them as expenses if the recommendations are acceptable, thus resetting all debts to zero.

Apps such as MoneyBuster or Splitwise have already implemented similar features.

Another improvement to the first step would be the ability to select one person to receive all payments, and then make payments to open recipients.

Thank you for developing this app continuously.

Cheers!

**Comment by TomBursch** [comment]
Thanks for the feedback! About Nr 1. If you click on the overview (top right corner in the balances tab) and scroll to the bottom you can see who owes how much to whom.
I'll add your second suggestion somewhere there.

**Comment by SimSon2710** [comment]
Perfect! And thanks for the quick reply :)
