### ISSUE TITLE
Feature request: Search icons

### ISSUE THREAD

**Issue by Rolv-Apneseth** [TomBursch/kitchenowl#228]
### What's the feature 🧐

When selecting an icon for an item, it would be nice if there was a quick search / filter to quickly find the appropriate icon.

### Extra information and references

 Not sure what the frontend is built with but `Ctrl+f` doesn't work as the text isn't in regular HTML nodes, so some other way of finding icons would be nice.

**Comment by Rolv-Apneseth** [comment]
Awesome, thank you

**Comment by SimSon2710** [comment]
Hey @TomBursch !

Icon search is a nice feature, but a big enhancement would be, if it was case insensitive. The first letter I type in the search text field is always upper case, but all icon names are lower case. So, if I search for 'Paprika' nothing shows up, although 'paprika' exists.

An even better enhancement but maybe overkill would be to make the search fuzzy. 

Cheers!

**Comment by TomBursch** [comment]
@SimSon2710 Should be fixed now. I don't think I'll add fuzzy search for icons, I would much rather prefer to improve the default items to a point where it isn't really needed to set the icons manually.
