### ISSUE TITLE
Feature request: Shopping List from meal plan

### ISSUE THREAD

**Issue by pinpox** [TomBursch/kitchenowl#238]
### What's the feature 🧐

I would like to be able to generate a shopping list from a mealplan. Couldn't find this functionality, let me know if it is already implemented.

My workflow would be something like:
- At the start of a week create a mealplan for the week by adding recipies to each day
- When done, create a shopping list for that meal plan
- Buy the stuff on that list so I have to go only shopping once a week and have everything I need to cook the recipies

**Comment by TomBursch** [comment]
Do you mean a new shopping list? Because you can already add all the items from your meal plan to the first shopping list.
![Screenshot_20230907-120657](https://github.com/TomBursch/kitchenowl/assets/9092682/f5d58c58-d0f1-409c-a0ea-d073662065f4)
