### ISSUE TITLE
Feature request: formatting

### ISSUE THREAD

**Issue by larieu** [TomBursch/kitchenowl#251]
### What's the feature 🧐

I am nit able to find this documented anywhere.

By pure luck I was able to find a nice formatting feature

I have wrote a recipe in the following format

> 
Ingredients:

'~~~~~~~~~~~~~'

1. ingredient 1 

2. ingredient 2

3. ...

'~~~~~~~~~~~~~'

Method 

Step1

Bla Bla bal

Step2

Bla bla bla

....

> 

as you can expect the ingredients part was nicely "highlighted" ( font is a little smaller ) like this

> 
Ingredients:

~~~~~~~~~~~~~

1. ingredient 1 

2. ingredient 2

3. ...

~~~~~~~~~~~~~

Method 

Step1

Bla Bla bal

Step2

Bla bla bla

....

> 

> IT WILL BE GREAT

 to heave a complete list of features like this 
eventually with "**bold**"/"_italic_"....

**Comment by TomBursch** [comment]
Yeah we should add those to the docs. FYI you can also @ the ingredients and it adds a pill at that spot with the amount (see #202)

**Comment by larieu** [comment]
For the moment ( to not over complicate things ) 
I think the best place where you can add this type of info is here:

https://docs.kitchenowl.org/reference/tips-and-tricks/

at least the following "tricks"

```
@Ingredient (exact match)  = pill (with additional qtty )
```


```
**Bold text** = bold
```
**Bold text** = bold

```
_ Italic text _ =  Italic
```

 _Italic text_  =  Italic

```
> before a phrase = "quoted" / or shifted
```
> before a phrase = "quoted" / or shifted

```
### add heading
```
### add heading

```
https://yourexternal.tld/your.url.of.choice = link to something else on the web
```
https://yourexternal.tld/your.url.of.choice = link to something else on the web

```
- aaa   = bullet
- bbb  = list
- ccc  = formatting
```
- aaa   = bullet
- bbb  = list
- ccc  = formatting

```
1. bla bla = number
2. bla bla = list 
3. bla bla = formating
```
1. bla bla = number
2. bla bla = list 
3. bla bla = formating

```
- [ ] checklist
- [ ] checklist
```
- [ ] checklist
- [ ] checklist

```
~~~
text in between 
this tilde
is smaller and highlighted
~~~
```
~~~
text in between 
this tilde
is smaller and highlighted
~~~

```
| Column_1 | Column_2 | .... | Column_n |
|-----|-----|-----|-----|
| Row_1 | text | ... | here |
| Row_2 | text | ... | here |
| ... | ... | ... | ... |
| Row_n | text | ... | here |
```

| Column_1 | Column_2 | .... | Column_n |
|-----|-----|-----|-----|
| Row_1 | text | ... | here |
| Row_2 | text | ... | here |
| ... | ... | ... | ... |
| Row_n | text | ... | here |

**Comment by TomBursch** [comment]
Thanks for the write-up! I've added it to the documentation and will add some more things in the future.

**Comment by vincemue** [comment]
could you add "It's case-insensitive and uses underscores for spaces." to the Ingredient pill on https://docs.kitchenowl.org/Tips-%26-Tricks/markdown/ ? 

I still have an issue to reference ingredients that contain"-" like "Erbsen-Möhren-Mischung". Is this somehow possible?

**Comment by TomBursch** [comment]
@vincemue I've updated the docs. Your hyphen issue is a bug which will be fixed in the next version.
