### ISSUE TITLE
Bug: Polling requests get a 400 error every time

### ISSUE THREAD

**Issue by lelutin** [TomBursch/kitchenowl#268]
### Is this urgent?

No

### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

v0.4.12 (83) | Server v80

### What's the problem 🤔

Assigning to backend since I can see the polling request get logged there and emitting the 400 error is logged there.

If I have my browser on a recipe page and I check with the firefox dev console what's happening, I can see that once every second there's a polling request and they all get a 400 error code response back.

I don't know if it is of any interest in this matter, but the request sent to the frontend by the client browser is made with HTTP2.

### Share your logs

```log
On the backend it looks like this in the logs:

~~~
[pid: 12|app: 0|req: 49514/49482] 10.0.2.100 () {58 vars in 1241 bytes} [Thu Oct 19 03:29:59 2023] POST /socket.io/?EIO=4&transport=polling&t=lnwmj31u&sid=1JXZppzDF8VBSGDqAB0p => generated 25 bytes in 0 msecs (HTTP/1.0 400) 1 headers in 54 bytes (3 switches on core 150)
~~~
```

### Share your configuration

```yml
nginx is installed as a service on the host machine with a debian package (version 1.22.1-9 on debian bookworm). nginx server block that points to the frontend:

~~~
server {                    
  listen 443 ssl http2;       
  listen [::]:443 ssl http2;
  server_name hostname_removed;
              
  ssl_certificate /etc/letsencrypt/live/hostname_removed/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/hostname_removed/privkey.pem;
  location / {
    proxy_pass http://[::1]:8081;
  }

}

server {
  listen 80;
  listen [::]:80;

  server_name hostname_removed;
  root /var/www/letsencrypt;

  location ~ ^/.well-known {
    try_files $uri $uri/ =404;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}
~~~

service setup -- rootless containers in a pod:

~~~
podman pod create --name kitchenowl -p 8081:80
podman run -d --restart always --pod kitchenowl --name ko_backend -e JWT_SECRET_KEY=secret_removed -v kitchenowl_data:/data docker.io/tombursch/kitchenowl:latest
podman run -d --restart always --pod kitchenowl --name ko_frontend -e BACK_URL=ko_backend:5000 docker.io/tombursch/kitchenowl-web:latest
~~~
```

**Comment by TomBursch** [comment]
I'm aware of this, this is only happening on the web, other platforms use web sockets which don't have that issue. If you set the `FRONT_URL` environment variable on the backend to the URL you're accessing it from, it should add the correct CORS headers to the polling request, which should fix this. I'm not sure why there even is a CORS issue, but since it only affects the real-time shopping list update on the web, I've left it like that.

**Comment by lelutin** [comment]
@TomBursch nice. adding the variable did solve the request errors, thanks!

I don't know much about the codebase.. is there a reason why the web clients are not using websockets whereas the others are?

**Comment by TomBursch** [comment]
> I don't know much about the codebase.. is there a reason why the web clients are not using websockets whereas the others are?

Because I wasn't sure why I did this, I leave this here for me as well:
socket.io does not support `extraHeaders` in browser web sockets (used for authorization in KitchenOwl). 

Cf. https://socket.io/docs/v4/client-options/#extraheaders
