### ISSUE TITLE
Feature request: Option to change recipe list into tiles with pictures.

### ISSUE THREAD

**Issue by vincemue** [TomBursch/kitchenowl#271]
### What's the feature 🧐

As a more visual person I would like to see the pictures of the recipes in the recipe list.

similar to what already exists in the meal plan:
![image](https://github.com/TomBursch/kitchenowl/assets/120366587/9776ae78-55ee-4913-a8e0-ae5b06445e67)

I also like the buttons to quickly add to the grocery list and meal plan.

**Comment by GRUUTio** [comment]
What is the plan for this? I would really like a visual grid to pick out recipes.

**Comment by TomBursch** [comment]
@GRUUTio it looks like there's a bug that never got fixed. If you don't have any recipe tags you won't see the button to change the viewing mode. If you add a recipe tag you should be able to switch to a grid view with images.

**Comment by GRUUTio** [comment]
Awesome, thanks a lot for the speedy response, sorry for replying to this old issue.
