### ISSUE TITLE
Bug: Importing recipe returns ERROR in config: 'IngredientText' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Nathanwoodburn** [TomBursch/kitchenowl#273]
### Is this urgent?

No

### What parts are affected

Both

### What are the Server/Client versions of KitchenOwl

latest docker

### What's the problem 🤔

When I import a recipe the frontend returns "An error occurred" with the docker logs for the backend showing the below

### Share your logs

```log
[pid: 28|app: 0|req: 586/585] 192.168.144.13 () {72 vars in 1559 bytes} [Fri Nov  3 11:03:28 2023] POST /socket.io/?EIO=4&transport=polling&t=loiic1h5&sid=UjI49mfbj3QCXQzVAAAG => generated 2 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 144 bytes (3 switches on core 198)
[2023-11-03 11:03:35,352] ERROR in config: 'IngredientText' object has no attribute 'strip'
ERROR:app.config:'IngredientText' object has no attribute 'strip'
[pid: 28|app: 0|req: 588/586] 192.168.144.13 () {72 vars in 1482 bytes} [Fri Nov  3 11:03:34 2023] POST /api/household/1/recipe/scrape => generated 20 bytes in 731 msecs (HTTP/1.1 500) 2 headers in 98 bytes (3 switches on core 198)
```

### Share your configuration

```yml
This is just using the default docker-compose from the website
```

**Comment by Nathanwoodburn** [comment]
@TomBursch has this been pushed to the :latest docker?
I just pulled the latest front and back and it is still having the same error

**Comment by TomBursch** [comment]
Should be available now, I didn't immediately publish a new backend version.

**Comment by Nathanwoodburn** [comment]
I've pulled the latest version but it is having a error ingredient quantity null. I'll send the full error in a few hrs when I get to my laptop.

**Comment by Nathanwoodburn** [comment]
Ok. I've had a look and some recipes work fine but some are giving this error (eg. https://www.allrecipes.com/recipe/20513/classic-waffles/)

> ERROR:app.config:'ParsedIngredient' object has no attribute 'quantity'
[2023-11-05 02:02:09,613] ERROR in config: 'ParsedIngredient' object has no attribute 'quantity'

**Comment by TomBursch** [comment]
You're right, it wasn't properly fixed. I published a new fixed version that should be live in ~20 min.

**Comment by Nathanwoodburn** [comment]
Awesome. I'll have a look and let you know if I find anything else

**Comment by Nathanwoodburn** [comment]
Looks all good
