### ISSUE TITLE
Bug: selfhosted on unraid can't connect to server via app

### ISSUE THREAD

**Issue by MitjaHenner** [TomBursch/kitchenowl#274]
### Is this urgent?

None

### What parts are affected

Both

### What are the Server/Client versions of KitchenOwl

App: 0.4.13, Server: 83

### What's the problem 🤔

I'm using unraid and have the server and web container installed via docker.
The web docker can reach the server via container-name, and I'm using Nginx Proxy Manager as reverse proxy to access the web version (Everything works fine there).

Now I want to use the android app, so I created a proxy host to the server: http://kitchen-owl:5000.

But when I tried to connect to the server it's not working and when I try the local address it gets stuck at the progress indicator.
Formats:
https://domain.com
192.168.0.20:5000

**Comment by TomBursch** [comment]
You have to enter the url of the web app, not the backend. That should solve your issue. The port 5000 doesn't need to be exposed outside the local machine.

**Comment by MitjaHenner** [comment]
Thanks, that worked.

**Comment by giacomocerquone** [comment]
Same here! Thanks for the solution and I also get where this is coming from: the images of KitchenOwl of the "community apps" section in Unraid state the following which is wrong at this point:

![Screenshot 2023-11-08 alle 10 12 01](https://github.com/TomBursch/kitchenowl/assets/9303791/65a36d02-fed9-4152-8a69-a80686fcd064)

It looks clearly like the installation of the WebUI is totally optional and the backend is more than enough to run the app. I guess if I can find that repo I'll add an issue there asking to change this description!

UPDATE: 

Just proposed the change, we'll see 🙂

**Comment by audas** [comment]
Sorry - does kitchenOwl-web exist? 

I am getting the "can't reach server" - is it mandatory to have  a FRONT_URL ? I wanted to access this locally as well as externally - ?
