### ISSUE TITLE
Bug: Missing reverse proxy examples for kitchenowl

### ISSUE THREAD

**Issue by jahway603** [TomBursch/kitchenowl#284]
### Is this urgent?

No

### What parts are affected

Both

### What is the server version

N/A

### What is the client version

N/A

### What platform are you using

Linux

### What's the problem 🤔

The Getting Started instructions here, https://docs.kitchenowl.org/self-hosting/, states "We recommend running KitchenOwl behind a reverse proxy with HTTPS (e.g. [nginx](https://nginx.org/en/docs/http/configuring_https_servers.html]))", but does not provide any reverse proxy examples.

### Share your logs

```Shell
N/A
```

### Share your configuration

```yml
N/A
```

**Comment by FX7** [comment]
I can share my apache config. So maybe this helps a bit.

The following assumptions are made by this config:
* You have a (sub)domain for your kitchenowl instance. eg: kitchenowl.example.org
* You are running the docker images from the given docker-compose.yml with the "ports" changed from "80:80" to "8080:80"
* You have certbot (or some other letsencrypt client) installed and running on your host system
* You have apache running on your host with the default ports for http/https (80/443)

Now you can save the following code in a seperated file (eg kitchenowl.conf) under /etc/apache/sites-available/

```
<VirtualHost *:80>
        ServerName kitchenowl.example.org
        ServerAdmin webmaster@example.org
        
        ErrorLog ${APACHE_LOG_DIR}/kitchenowl_error.log
        CustomLog ${APACHE_LOG_DIR}/kitchenowl_access.log combined
        
        Redirect permanent / https://kitchenowl.example.org
</VirtualHost>

<VirtualHost *:443>
        ServerName kitchenowl.example.org
        ServerAdmin webmaster@example.org

        <IfModule mod_headers.c>
                Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains; preload"
        </IfModule>


        ErrorLog ${APACHE_LOG_DIR}/kitchenowl_error.log
        CustomLog ${APACHE_LOG_DIR}/kitchenowl_access.log combined

        ProxyPass / http://localhost:8080/
        ProxyPassReverse / http://localhost:8080/

SSLCertificateFile /etc/letsencrypt/live/kitchenowl.exaample.org/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/kitchenowl.example.org/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

Afterwards you can reload apache with

`systemctl reload apache2.service`

Now you can access your kitchenowl instance under https://kitchenwol.example.org

**Comment by jahway603** [comment]
Thank you for this @FX7 

I use nginx and was able to get this working, so this is my nginx reverse proxy example:
```
server {
    server_name kitchenowl.example.org;
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot

    # https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/
    #add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        proxy_pass http://localhost:8800;
    }

    ssl_certificate /etc/letsencrypt/live/kitchenowl.example.org/fullchain.pem; # managed by
 Certbot
    ssl_certificate_key /etc/letsencrypt/live/kitchenowl.example.org/privkey.pem; # managed 
by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = kitchenowl.example.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name kitchenowl.example.org;
    listen 80;
    listen [::]:80;
    return 404; # managed by Certbot
}
```

I'm not sure about the `add_header` and if that is necessary for Kitchenowl.

Your reverse proxy example and my example can be included in this project, but I still need to determine if that `add_header` is necessary.

**Comment by FX7** [comment]
The "add_header" part in nginx is the same as the "<IfModule mod_headers.c>" for apache.
It is not necessary. But it tells the client (Browser) that this site should only be used with https. So a down grade (to http) man in the middle attack is not possible (or at least harder ;-)

So this is mainly a security feature but one that doenst hurt and should be active.

**Comment by TomBursch** [comment]
@FX7 is correct. Thanks for your setups, I've added them as a starting point to https://docs.kitchenowl.org/self-hosting/reverse-proxy/
