### ISSUE TITLE
Bug: Missing Documentation to update kitchen owl server

### ISSUE THREAD

**Issue by jahway603** [TomBursch/kitchenowl#299]
### Is this urgent?

No

### What parts are affected

Both

### What is the server version

N/A

### What is the client version

N/A

### What platform are you using

Android, Linux

### What's the problem 🤔

Missing Documentation to update kitchen owl server

### Share your logs

```Shell
N/A
```

### Share your configuration

```yml
N/A
```

**Comment by TomBursch** [comment]
To upgrade a docker compose stack, you can simply run:
```
docker compose pull
docker compose up -d
```

I'll add it to the docs.
