### ISSUE TITLE
Feature request: Allow changing port of backend or frontend via envvar

### ISSUE THREAD

**Issue by stavros-k** [TomBursch/kitchenowl#30]
### What's the feature 🧐

Trying to wrap this project's container into a helm chart for TrueCharts catalog. (Native helm + TrueNAS scale catalog).

But having 2 containers with same port (80) into the same k8s pod is not possible.
While I can split back and front in to 2 different pods, this will impact the ease of use we try to provide for the users.

I propose to allow changing the port via env var as it will still work with the default (80) for current users, but still allow others to change.

**Comment by TomBursch** [comment]
I'm not familiar with k8s pods, but it doesn't work even though port 80 on the backend doesn't need to be exposed? Can it not just listen there but nothing is routed to it? Either way I'll add such an environment variable, I guess it won't hurt.

**Comment by stavros-k** [comment]
> I'm not familiar with k8s pods, but it doesn't work even though port 80 on the backend doesn't need to be exposed? Can it not just listen there but nothing is routed to it? Either way I'll add such an environment variable, I guess it won't hurt.

It can't start at all, as it complains that the port is already in use.
All containers in the same pod share the same network namespace, and can't have the same port binded to more than one containers.


Variable should work!

Thanks!
