### ISSUE TITLE
Bug: Blank Expense overview

### ISSUE THREAD

**Issue by irishrain** [TomBursch/kitchenowl#305]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

v88

### What is the client version

v0.4.17

### What platform are you using

Android, Web

### What's the problem 🤔

I added some expenses today and wanted to see the statistics for the different categories. This is how it looked in the Android app:
![Screenshot_20231129-225448](https://github.com/TomBursch/kitchenowl/assets/74204581/8cfcc3ef-f049-4885-ad7a-3ac36dd915d9)
I also checked with the webapp, but got the same result.

Nothing out of the ordinary in the logs, everything else works fine.

### Share your logs

```Shell
Backend:
[pid: 29|app: 0|req: 8403/8402] 192.168.18.1 () {36 vars in 714 byte
s} [Wed Nov 29 21:57:52 2023] GET /api/household/1 => generated 695
bytes in 23 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches o
n core 198)
[pid: 29|app: 0|req: 8404/8403] 192.168.18.1 () {36 vars in 752 byte
s} [Wed Nov 29 21:57:52 2023] GET /api/household/1/expense/categorie
s => generated 2078 bytes in 21 msecs (HTTP/1.1 200) 2 headers in 73
 bytes (3 switches on core 197)
[pid: 29|app: 0|req: 8405/8404] 192.168.18.1 () {36 vars in 743 byte
s} [Wed Nov 29 21:57:52 2023] GET /api/household/1/expense?view=0 =>
 generated 16512 bytes in 74 msecs (HTTP/1.1 200) 2 headers in 74 by
tes (3 switches on core 198)
[pid: 29|app: 0|req: 8406/8405] 192.168.18.1 () {36 vars in 752 byte
s} [Wed Nov 29 21:57:54 2023] GET /api/household/1/expense/categorie
s => generated 2078 bytes in 22 msecs (HTTP/1.1 200) 2 headers in 73
 bytes (3 switches on core 198)
[pid: 29|app: 0|req: 8407/8406] 192.168.18.1 () {36 vars in 714 byte
s} [Wed Nov 29 21:57:54 2023] GET /api/household/1 => generated 695
bytes in 24 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches o
n core 197)
[pid: 29|app: 0|req: 8408/8407] 192.168.18.1 () {36 vars in 809 byte
s} [Wed Nov 29 21:57:54 2023] GET /api/household/1/expense/overview?
view=0&frame=2&steps=11&page=0 => generated 1211 bytes in 62 msecs (
HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 198)

Frontend:
192.168.18.1 - - [29/Nov/2023:22:06:48 +0000] "GET /api/household/1/
expense?view=0 HTTP/1.1" 200 16512 "-" "Dart/3.2 (dart:io)" "46.223.
149.92"
192.168.18.1 - - [29/Nov/2023:22:06:48 +0000] "GET /api/household/1/
expense/categories HTTP/1.1" 200 2078 "-" "Dart/3.2 (dart:io)" "46.2
23.149.92"
192.168.18.1 - - [29/Nov/2023:22:06:48 +0000] "GET /api/household/1
HTTP/1.1" 200 695 "-" "Dart/3.2 (dart:io)" "46.223.149.92"
192.168.18.1 - - [29/Nov/2023:22:06:49 +0000] "GET /api/household/1
HTTP/1.1" 200 695 "-" "Dart/3.2 (dart:io)" "46.223.149.92"
192.168.18.1 - - [29/Nov/2023:22:06:49 +0000] "GET /api/household/1/
expense/overview?view=0&frame=2&steps=11&page=0 HTTP/1.1" 200 1211 "
-" "Dart/3.2 (dart:io)" "46.223.149.92"
192.168.18.1 - - [29/Nov/2023:22:06:49 +0000] "GET /api/household/1/
expense/categories HTTP/1.1" 200 2078 "-" "Dart/3.2 (dart:io)" "46.2
23.149.92"
127.0.0.1 - - [29/Nov/2023:22:07:09 +0000] "GET / HTTP/1.1" 200 3413
 "-" "curl/8.4.0" "-"
```

**Comment by TomBursch** [comment]
Thanks for the bug report! I fixed this already and the version with the fix should be live soon.

**Comment by irishrain** [comment]
Thank you for the quick fix!

I was wondering: How do you test before creating a new release? Do you have an automated testsuite? The test folder seems to be pretty empty. If you are interested, I might be able to help.

**Comment by TomBursch** [comment]
> I was wondering: How do you test before creating a new release? Do you have an automated testsuite? The test folder seems to be pretty empty. If you are interested, I might be able to help.

I have set up an automated test workflow but haven't created many tests 😅 If you have some time, feel free to add as many tests as you want. Especially on the backend, there is still some work to do with setting up a test environment with a temporary database and filling that with some data. Please don't hesitate to text me on matrix if you have any questions.
