### ISSUE TITLE
Bug: nlohmann::json_abi_v3_11_2::detail::type_error on Manjaro Linux

### ISSUE THREAD

**Issue by EgidioCaprino** [TomBursch/kitchenowl#313]
### Is this urgent?

Yes

### What parts are affected

Frontend

### What is the server version

v91

### What is the client version

v0.4.19

### What platform are you using

Linux

### What's the problem 🤔

Getting this error when clicking `Switch Server` in the login page:

```
$ kitchenowl

(kitchenowl:10285): Gdk-CRITICAL **: 21:55:09.000: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
flutter: dynamic_color: Accent color detected.
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::type_error'
  what():  [json.exception.type_error.307] cannot use erase() with null
zsh: IOT instruction (core dumped)  kitchenowl
```

**Comment by TomBursch** [comment]
What distro are you on? Did you run the executable directly or install the deb or rpm file? Can you try installing `libsecret-1-0` and `libjsoncpp1` (or the equivalent of your distro) and see if that helps?

**Comment by EgidioCaprino** [comment]
Hi @TomBursch, thank you for your reply 🙏

I'm on Manjaro Gnome 23.1.0. These are the two packages installed on my system:

```
local/libsecret 0.21.1-1
    Library for storing and retrieving passwords and other secrets

local/jsoncpp 1.9.5-2
    C++ library for interacting with JSON
```

I'm extracting the `tar.gz` archive:

[Screencast from 2023-12-07 10-07-19.webm](https://github.com/TomBursch/kitchenowl/assets/5156120/a7180747-68b3-4efc-9d5d-494ad72c121c)

I'm the maintainer of the [kitchenowl](https://aur.archlinux.org/packages/kitchenowl) package on AUR and it used to work with previous versions

**Comment by TomBursch** [comment]
Apparently, an exception was thrown if the app's secret was empty when trying to delete something inside it. I've added a check to only delete keys if they exist, which should solve this.

Additionally, from what I've found, `libjsoncpp1` is not needed anymore.

Thanks for maintaining the AUR package!

**Comment by EgidioCaprino** [comment]
Awesome, thank you 😃 I'll test it again with the next release then
