### ISSUE TITLE
Bug: Duplication of ingridients ending with Öl

### ISSUE THREAD

**Issue by LDaxin** [TomBursch/kitchenowl#314]
### Is this urgent?

No

### What parts are affected

Backend

### What is the server version

V91

### What is the client version

v0.4.19

### What platform are you using

Android, Web

### What's the problem 🤔

If a ingridient with the letter Öl at the end gets selectet a duplicate gets created. This is just with the Öl at the end with Öln, Ön, öl or testÖL at the end it's not happening just with the upper case Letter Ö and the lower case Letter l. The code of the Letters in the JSON Export is \u00D6l. 

![2023-12-04-223818_crop](https://github.com/TomBursch/kitchenowl/assets/46381046/1c4a2e43-2f1a-45df-bb47-b8b6a6642904)

This hapens in Android and in the Web version.

I hope this is helpfull

**Comment by LDaxin** [comment]
the Renaming of the ingredients makes no difference. if the ingredient was originally created with Öl at the end it will Duplikate even wenn renamed.

**Comment by LDaxin** [comment]
okay sorry for correcting me again I have played around a little more and it seems that the problem is with the uppercase Ö and the l is not so important. what I mean I can recreate the duplication with adding the ingredient from the recently used with just Ö in the ingredient name and it is not important if there is a another letter

**Comment by TomBursch** [comment]
> okay sorry for correcting me again 

No worries, thank you for testing this so much!

**Comment by LDaxin** [comment]
I tested it a little bit further the uppercase Ä and Ü are although affected.
