### ISSUE TITLE
Feature request: add ability to authenticate with OIDC / OAuth2

### ISSUE THREAD

**Issue by alexanderadam** [TomBursch/kitchenowl#32]
### What's the feature 🧐

I guess this is similar to #28 but probably simpler to implement.
Many selfhosting users are already using services who can act as an OpenID Connect provider (i.e. [Kanidm](https://kanidm.github.io/kanidm/stable/), Authelia, Keycloak, Authentik, GitLab, Gitea, Nextcloud or similar).

Also instead implementing LDAP logic, OpenID libraries usually need far less code and [there are many libraries available for all popular languages](https://openid.net/developers/certified/).

So I guess this would be a nice addition.

### Extra information and references

Thank you so much for Kitchenowl! :star_struck:

**Comment by TheLonelinessOfHS** [comment]
+1 to watchlist. When it's implemented I will start using this xD.

**Comment by TomBursch** [comment]
This is finally implemented. I would still consider this beta, feel free to try this out (when the next version is released) and report back any bugs you encounter. The setup documentation can be found here: https://docs.kitchenowl.org/self-hosting/oidc/

**Comment by TheLonelinessOfHS** [comment]
> This is finally implemented. I would still consider this beta, feel free to try this out (when the next version is released) and report back any bugs you encounter. The setup documentation can be found here: https://docs.kitchenowl.org/self-hosting/oidc/

Hi, thanks a lot for implementing this. One morething is that would it be possible to allow automatic creation of users with OIDC? I am using my own identity manager and do not want users to register an account manually.

**Comment by TomBursch** [comment]
> > This is finally implemented. I would still consider this beta, feel free to try this out (when the next version is released) and report back any bugs you encounter. The setup documentation can be found here: https://docs.kitchenowl.org/self-hosting/oidc/
> 
> Hi, thanks a lot for implementing this. One morething is that would it be possible to allow automatic creation of users with OIDC? I am using my own identity manager and do not want users to register an account manually.

Yes, accounts are automatically created when signing in using OIDC. I will update the docs to state that a bit more clearly.

**Comment by heliohenriques** [comment]
Hi,
Let me start to say what wonderful project.
Regarding OIDC, I tried to implement with Authentik, but the "Sign in with OIDC" is not available.
Any trick?
Thank you

**Comment by hypervtechnics** [comment]
I tried as well. It seems the docker image was not updated yet.

**Comment by TomBursch** [comment]
It is now https://github.com/TomBursch/kitchenowl/releases/tag/v0.4.15 😄

**Comment by kaybi-gh** [comment]
Thank you for implementing OIDC 🚀 
I installed v0.4.15 and configured OIDC with Authentik!
The button Sign in with OIDC is appearing but when I click on it the URI https://kitchenowl.fqdn/api/auth/oidc?provider=custom returns a 500 with message `Something went wrong`.
In the logs I've got this:
```
[pid: 46|app: 0|req: 15/15] 10.32.30.254 () {62 vars in 990 bytes} [Thu Nov 16 15:56:30 2023] GET /api/auth/oidc?provider=custom => generated 20 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 98 bytes (3 switches on core 199)
16/11/2023
16:56:44
[2023-11-16 15:56:44,667] ERROR in config: 'kitchenowl_scheme'
```

**Comment by TomBursch** [comment]
You're right, there was a bug in the backend. I've published a new version that should fix that. You can re-pull the latest image when the [pipeline](https://github.com/TomBursch/kitchenowl-backend/actions/runs/6894496872) has succeeded

**Comment by kaybi-gh** [comment]
I confirm this is now working with the latest image, kudos! 🚀

**Comment by heliohenriques** [comment]
Yes, it's working.
Only one note when Logout. The token is revoked, but the redirection is not working properly. 
There is no possibility of add Logout URL?

**Comment by hypervtechnics** [comment]
@heliohenriques I saw you also use Authentik. Did you need to do anything special? I configured everything and after trying to link an account nothing happens and I get stuck in a redirect loop :/

EDIT: Confused the names, sorry for the unnecessary ping :/

**Comment by heliohenriques** [comment]
I had the same issue with a redirecting loop when you link an account. 
It works well with a new user. I tested to check if the problem was with the "link account". Other user with other email. 
@TomBursch, and trick to link account?

**Comment by TomBursch** [comment]
> Only one note when Logout. The token is revoked, but the redirection is not working properly.
There is no possibility of add Logout URL?

Can you further explain what you mean? Or provide part of the specification you mean?

**Comment by TomBursch** [comment]
Can you guys provide the backend logs of the unsuccessful account link? 

Also does OIDC work on android for you with the custom scheme redirect?

**Comment by kaybi-gh** [comment]
> Can you guys provide the backend logs of the unsuccessful account link?
> 
> Also does OIDC work on android for you with the custom scheme redirect?

I confirm OIDC works on android with the custom scheme redirect 👍

**Comment by heliohenriques** [comment]
> > Only one note when Logout. The token is revoked, but the redirection is not working properly.
> > There is no possibility of add Logout URL?
> 
> Can you further explain what you mean? Or provide part of the specification you mean?

Sure,
After logout, the page it started looping  /signing/redirecting...
My question is that we don't define any Logout URL like https://<DOMAIN>/application/o/kitchenowl/end-session/

**Comment by TomBursch** [comment]
Okay, both of those bugs (linking and logout) should be fixed in the next release.

**Comment by hypervtechnics** [comment]
Can confirm linking does now work as expected :) Thanks for the quick fix!

**Comment by heliohenriques** [comment]
Thank you @TomBursch.
It's working perfectly. 
Suggestion for the future, option to disable local login, or option to redirect automatically to OIDC on login page.
