### ISSUE TITLE
Bug: Clicking on individual ingredients in recipe only de-selects them

### ISSUE THREAD

**Issue by schnillerman** [TomBursch/kitchenowl#334]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

public/official server

### What is the client version

0.4.20 Android

### What's the problem 🤔

Clicking on individual ingredients in a recipe de-selects them without any result.
Going out and back into recipe results in all ingredients listed and selected.
I would expect for individually clicked ingredients to be added to a shopping list (if several lists exist, ask which shopping list to be used).

**Comment by TomBursch** [comment]
I'm a bit confused about this issue, after selecting the items of a recipe, you can click on `add X to shopping list` (at the bottom), which adds them to the primary/first shopping list. What behavior is missing in your opinion?

> (if several lists exist, ask which shopping list to be used)

This is not the case and valid request #333

**Comment by schnillerman** [comment]
I didn't see the button because it was hidden by my screen border, and I didn't scroll down far enough.

A hovering button on the bottom of the screen might make sense?

**Comment by schnillerman** [comment]
Please change label to "enhancement" or similar

**Comment by TomBursch** [comment]
I'll close this then in favor of #347 🙂
