### ISSUE TITLE
Feature request: Highlight shopping lists with unchecked items

### ISSUE THREAD

**Issue by schnillerman** [TomBursch/kitchenowl#335]
### What's the feature 🧐

Shopping lists with unchecked items (still to be bought) should have a different color in the shopping view in order not to forget things in different lists.
Also, they should be listed before any empty lists.

**Comment by TomBursch** [comment]
I think instead of changing the color, showing the number of remaining items per list behind the name would provide additional information and solve this at the same time.

**Comment by schnillerman** [comment]
Of course, that's a good idea. Maybe a compromise would be to fade out the lists with 0 remaining items a little more.

HAPPY HOLIDAYS! 🎄

**Comment by schnillerman** [comment]
I specified this now in #336. This one can be closed.
