### ISSUE TITLE
Feature request:  List all unchecked shopping items in list header/chip

### ISSUE THREAD

**Issue by schnillerman** [TomBursch/kitchenowl#336]
### What's the feature 🧐
If there are unchecked items in different lists, they might easily be overlooked.
Therefore I propose to
- show number of unchecked shopping items in list headers (see attached mock-up)
- move lists with unchecked items in front and
- highlight lists with unchecked items with different color (e.g., different brightness)

![Screenshot_20240208_165050.jpg](https://github.com/TomBursch/kitchenowl/assets/17252473/bd797931-1e60-4a57-b167-8b161d0a94e9)

**Comment by schnillerman** [comment]
Can I prioritize this with another donation? 🙄

**Comment by TomBursch** [comment]
> Can I prioritize this with another donation? 🙄

Hey, sorry that this is taking so long. I started work on it, but it wasn't as straight forwards as I initially hoped. I then forgot about this a little bit. Thanks for the reminder, I'll do this next. But it will take some time as I'm a bit busy with my master's thesis. 

Also, you won't need to donate for it to get done. It'll eventually 😄

**Comment by schnillerman** [comment]
Oh wow - all the best for your Masterarbeit! May I ask what the title will be?

**Comment by schnillerman** [comment]
Oh wow - all the best for your Masterarbeit! May I ask what the title will be?

**Comment by TomBursch** [comment]
Thanks! Sure, it's called Interaction Testing Hierarchical Component and Connector Languages

**Comment by schnillerman** [comment]
This came out brilliant !!! 🚀 

I didn't realize it was implemented because apparently F-Droid didn't/doesn't yet have the update? Google Play sure does.
