### ISSUE TITLE
Missing characters when adding new items

### ISSUE THREAD

**Issue by irishrain** [TomBursch/kitchenowl#37]
When adding a new, never before bought item to the list, there are often missing characters at the end of the word (gets worse with faster typing).

![Screenshot_20220929-180510](https://user-images.githubusercontent.com/74204581/193082177-bd2a05a5-e927-4f0d-991d-678760794192.png)

The only way to get the correct entry is to delete the last character and write it again, which works two thirds of the time.

PS: Thanks a lot for this great app, and thanks for implementing all of my previous tickets!

**Comment by TomBursch** [comment]
Thanks for the issue(s)! I'm aware of this issue, I'll fix it next week when I'm back from my vacation.
