### ISSUE TITLE
Feature request: Reset ingredient symbol

### ISSUE THREAD

**Issue by schnillerman** [TomBursch/kitchenowl#375]
As a shopping list editor, I want to reset an ingredient symbol to nothing instead of having to delete it and create it newly.

**Comment by TomBursch** [comment]
Do you mean the icon of an item? You can click on the selected icon again, which will deselect it. But yeah, it should probably have an explicit remove icon button 😄

**Comment by schnillerman** [comment]
Ah I didn't know this. I wonder how this could be made more obvious. Maybe a small size font hint on top of the icon list: "click selected icon to remove"
