### ISSUE TITLE
Feature request: Show editable attributes below ingredient instead of in menu

### ISSUE THREAD

**Issue by schnillerman** [TomBursch/kitchenowl#378]
### What's the feature 🧐

As an ingredient editor, I want to change the following attributes without having to go into 3-dot-menu since there is plenty of real estate in the ingredient detail view:

- change symbol (could be realized by showing its symbol tile anyway and also showing a reset button to remove symbol)
- rename (could be realized by showing an editing pen next to name
- merge (could be realized by showing a merge symbol)
- delete (could be realized by showing a trash can next to edit name symbol)

**Comment by Timoses** [comment]
This applies to shopping list as well. When changing the symbol of an item it's annoying to
1. go into the item's description menu
2. go into the 3-dot menu

It's a lot of clicks.

**Comment by TomBursch** [comment]
Hmm, I'm unsure if I like the idea. Really, how often do you edit an icon? I get that it's a lot of clicks, but it's also a really infrequent operation. 

Additionally, the [material guidelines](https://m3.material.io/components/top-app-bar/guidelines#b1b64842-7d88-4c3f-8ffb-4183fe648c9e) say that one should use 3 App Bar actions max.

**Comment by Timoses** [comment]
> Hmm, I'm unsure if I like the idea. Really, how often do you edit an icon? I get that it's a lot of clicks, but it's also a really infrequent operation.

It depends. Once you're settled with everything it should be infrequent.
The initial ingredients are all English. Adding the desired items in the beginning requires lots of interactions with that menu.

IMO, the 3-dot menu could go away, so in the ingredient options menu one has:
* description
* rename
* change icon

all available with one click of a button.

**Comment by TomBursch** [comment]
> The initial ingredients are all English. Adding the desired items in the beginning requires lots of interactions with that menu.

This shouldn't be the case, when creating a household you can select the language you want to start with (If yours isn't there, feel free to [translate](https://hosted.weblate.org/projects/kitchenowl/default-items/) them) or start with an empty item list.

**Comment by TomBursch** [comment]
In the next version, there will be a dedicate item list inside the household settings where you can see all items ever created and if you edit items from there you will have dedicated buttons below the category selection for renaming/changing the icon/deleting and so on.  I think this is a good solution for editing multiple items fast, while also keeping the long press item page clean and not cluttered with too many options.
