### ISSUE TITLE
(iOS) Text fields get emptied when tapping other text fields

### ISSUE THREAD

**Issue by LeoKlaus** [TomBursch/kitchenowl#4]
iPhone 11 Pro Max, iOS 15.3 (Beta)

Whenever I tap another text field in the login form, all text fields in that form get emptied. I was able to log in once (currently trying to replicate this) but am now effectively locked out of the app.

It looks like the entire view is redrawn whenever I tap one of the textfields.

![bug](https://user-images.githubusercontent.com/66492595/150655613-f8093c94-7661-4292-9e6b-6ea48ff44cb9.gif)

**Comment by TomBursch** [comment]
I confirmed the bug and have a suspicion where it's coming from, will report back when its fixed.

**Comment by TomBursch** [comment]
So, I don't think this is an issue with my code, more so with flutter and ios 15.3. It works fine with ios 15.2 and right now I'm waiting for full ios 15.3 support in xcode stable (https://xcodereleases.com/).
