### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [TomBursch/kitchenowl#41]
It would be great if there was a way to translate KitchenOwl later

**Comment by TomBursch** [comment]
So to make it easier in the future I've set up a translation tool. Anyone interested can join here: https://hosted.weblate.org/engage/kitchenowl/

Edit: I changed the tool I'll be using

**Comment by mondlicht-und-sterne** [comment]
thank you ;)

oh you can't add new languages :-/

**Comment by TomBursch** [comment]
I've changed the tool, this one seems way better and it should allow to add new languages.
