### ISSUE TITLE
Connecting Android App to self hosted service?

### ISSUE THREAD

**Issue by nicoKoehler** [TomBursch/kitchenowl#413]
Hi 

First off, thanks for developing this app. It fills a crucial need when trying to move away from the corporate cloud. 

I am currently hosting the app on my server, implemented via the docker-compose.yml you have in the repo. 
I am trying to connect the Android app to this server now, by clicking "Switch server" in the app and then entering the IP address. 

However, the loading circle just keeps spinning indefinitely.
I tried:

- just connecting to the IP
- IP + standard port of the backend (5000) 
- With port 5000 exposed via docker compose, enabled and disabled

The docs are not really clear how to achieve this, so I am not sure if this is a bug or if I am just being a moron :)

**Comment by TomBursch** [comment]
Hi, you just have to enter the same address you would enter in your web browser. You don't need to expose port 5000 on the backend (it's not a http server). Hope that helps.

**Comment by nicoKoehler** [comment]
@TomBursch should have added that I already tried that, using my web address.
However, the idiot was me after all, as I did not put the http:// in front of the IP. Just used to not having to do it from the browser. Works now!
