### ISSUE TITLE
Bug: E-mail confirmation contains local http://localhost:8222

### ISSUE THREAD

**Issue by robotter112** [TomBursch/kitchenowl#423]
### Is this urgent?

No

### What parts are affected

Backend

### What is the server version

v93

### What is the client version

v0.4.21 (92)

### What platform are you using

Web

### What's the problem 🤔

When I send the confirmation email to a user, the confirmation link does not contain the domain 
`http://localhost:8222/confirm-email?t=e627f854787d42246p18a541bacf65cdf30.`

However, I have set the environment in the backend container:
FRONT_URL: `https://shopping.domain.de`

### Share your logs

```Shell
I haven't found anything relevant in the logs.
```

### Share your configuration

```yml
KitchenOwl-Web:
BACK_URL=192.168.0.010:5000

KitchenOwl:
FRONT_URL=https://shopping.domain.de
SMTP_HOST=mail.domain.de
SMTP_PORT=465
SMTP_USER=noreply@domain.de
SMTP_FROM=noreply@domain.de
SMTP_PASS=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by TomBursch** [comment]
Have you tried restarting the backend? Whenever you change an environment variable you'll need to restart it.

**Comment by robotter112** [comment]
Yes, I have restarted both containers, but the link in the email is still incorrect.

**Comment by TomBursch** [comment]
I've just published a new version, can you confirm if this is still happening?

**Comment by robotter112** [comment]
I have previously updated to version 0.5.0 (94)

I registered with a new e-mail and the confirmation link still looks the same.
`http://localhost:8222/confirm-email?t=775d2455647241ad8109e58dbbf20d67`

**Comment by robotter112** [comment]
I did some more trial and error and found that it also uses `http://localhost:8222/signin/redirect` as the redirect URL for SSO.

I don't know if I already mentioned it, but my kitchenowl is running in unraid.

**Comment by TomBursch** [comment]
> I don't know if I already mentioned it, but my kitchenowl is running in unraid.

That explains it. You can create an issue for this with the unraid template maintainer here https://codeberg.org/HanSolo97/unraid-template-kitchenowl
