### ISSUE TITLE
Ingredients Not importing

### ISSUE THREAD

**Issue by everything123** [TomBursch/kitchenowl#427]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

v95

### What is the client version

v0.5.0

### What platform are you using

iOS, Web, Mac, Windows

### What's the problem 🤔

When importing recipes, i need to manually add icons for all ingredients, nothing auto-adds. Im not 100% sure if this is even a bug or just not a feature added, I cant find much info on this project.
<img width="1411" alt="Screenshot 2024-04-06 at 6 50 00 PM" src="https://github.com/TomBursch/kitchenowl/assets/33844597/bc7c0932-5f76-4d37-80e7-d28cfc7133fb">

**Comment by everything123** [comment]
LOGS:

text  error  warn  system  array  login  

[pid: 140|app: 0|req: 202/201] 10.0.0.243 () {46 vars in 2476 bytes} [Sat Apr  6 17:44:14 2024] GET /socket.io/?EIO=4&transport=polling&t=luoswluu => generated 97 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 100 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 203/202] 10.0.0.243 () {46 vars in 2403 bytes} [Sat Apr  6 17:44:14 2024] GET /api/user => generated 835 bytes in 24 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 204/203] 10.0.0.243 () {52 vars in 2658 bytes} [Sat Apr  6 17:44:15 2024] POST /socket.io/?EIO=4&transport=polling&t=luoswlv4&sid=5SVMxSDtSdoGrTSkAAAP => generated 25 bytes in 0 msecs (HTTP/1.1 400) 1 headers in 54 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 206/204] 10.0.0.243 () {52 vars in 2658 bytes} [Sat Apr  6 17:44:15 2024] POST /socket.io/?EIO=4&transport=polling&t=luoswlvy&sid=5SVMxSDtSdoGrTSkAAAP => generated 25 bytes in 0 msecs (HTTP/1.1 400) 1 headers in 54 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 207/205] 10.0.0.243 () {46 vars in 2417 bytes} [Sat Apr  6 17:44:15 2024] GET /api/household/1 => generated 687 bytes in 29 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 208/206] 10.0.0.243 () {46 vars in 2443 bytes} [Sat Apr  6 17:44:15 2024] GET /api/household/1/shoppinglist => generated 99 bytes in 17 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 209/207] 10.0.0.243 () {46 vars in 2425 bytes} [Sat Apr  6 17:44:15 2024] GET /api/household/1/tag => generated 3 bytes in 18 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 196)
[pid: 140|app: 0|req: 210/208] 10.0.0.243 () {46 vars in 2431 bytes} [Sat Apr  6 17:44:15 2024] GET /api/household/1/recipe => generated 6402 bytes in 57 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 211/209] 10.0.0.243 () {46 vars in 2433 bytes} [Sat Apr  6 17:44:15 2024] GET /api/household/1/planner => generated 3 bytes in 20 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 196)
[pid: 140|app: 0|req: 212/210] 10.0.0.243 () {46 vars in 2463 bytes} [Sat Apr  6 17:44:15 2024] GET /api/household/1/planner/recent-recipes => generated 3 bytes in 26 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 213/211] 10.0.0.243 () {46 vars in 2469 bytes} [Sat Apr  6 17:44:15 2024] GET /api/household/1/planner/suggested-recipes => generated 3 bytes in 37 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 196)
[pid: 140|app: 0|req: 214/212] 10.0.0.243 () {46 vars in 2474 bytes} [Sat Apr  6 17:44:15 2024] GET /api/household/1/expense/categories => generated 3 bytes in 32 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 215/213] 10.0.0.243 () {46 vars in 2465 bytes} [Sat Apr  6 17:44:15 2024] GET /api/household/1/expense?view=0 => generated 3 bytes in 23 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 196)
[pid: 140|app: 0|req: 216/214] 10.0.0.243 () {46 vars in 2473 bytes} [Sat Apr  6 17:44:15 2024] GET /api/shoppinglist/1/items?orderby=0 => generated 1326 bytes in 33 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 217/215] 10.0.0.243 () {46 vars in 2454 bytes} [Sat Apr  6 17:44:15 2024] GET /api/household/1/category => generated 1666 bytes in 28 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 196)
[pid: 140|app: 0|req: 218/216] 10.0.0.243 () {46 vars in 2483 bytes} [Sat Apr  6 17:44:15 2024] GET /api/shoppinglist/1/recent-items?limit=9 => generated 3 bytes in 44 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 218/217] 10.0.0.243 () {46 vars in 2526 bytes} [Sat Apr  6 17:44:15 2024] GET /socket.io/?EIO=4&transport=polling&t=luoswlv4&sid=5SVMxSDtSdoGrTSkAAAP => generated 1 bytes in 24976 msecs (HTTP/1.1 200) 2 headers in 100 bytes (3 switches on core 199)
[pid: 140|app: 0|req: 219/218]  () {16 vars in 245 bytes} [Sat Apr  6 17:44:57 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
[pid: 140|app: 0|req: 220/219] 73.65.198.207 () {34 vars in 759 bytes} [Sat Apr  6 17:45:50 2024] GET /api/household/1/tag => generated 3 bytes in 44 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 199)
[pid: 140|app: 0|req: 221/220] 73.65.198.207 () {34 vars in 751 bytes} [Sat Apr  6 17:45:50 2024] GET /api/household/1 => generated 687 bytes in 46 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 199)
[pid: 140|app: 0|req: 222/221] 73.65.198.207 () {34 vars in 765 bytes} [Sat Apr  6 17:45:50 2024] GET /api/household/1/recipe => generated 6402 bytes in 113 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 223/222]  () {16 vars in 245 bytes} [Sat Apr  6 17:45:57 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 224/223] 73.65.198.207 () {38 vars in 878 bytes} [Sat Apr  6 17:46:16 2024] POST /api/household/1/recipe/scrape => generated 4000 bytes in 1399 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 225/224]  () {16 vars in 245 bytes} [Sat Apr  6 17:46:58 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 226/225]  () {16 vars in 245 bytes} [Sat Apr  6 17:47:58 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 226/226] 73.65.198.207 () {46 vars in 1030 bytes} [Sat Apr  6 17:43:32 2024] GET /socket.io/?EIO=4&transport=websocket => generated 175 bytes in 295976 msecs (HTTP/1.1 101) 4 headers in 164 bytes (2 switches on core 197)
[pid: 140|app: 0|req: 227/227]  () {16 vars in 245 bytes} [Sat Apr  6 17:48:59 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 228/228] 10.0.0.243 () {52 vars in 2600 bytes} [Sat Apr  6 17:49:51 2024] POST /api/household/1/recipe/scrape => generated 2592 bytes in 1738 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 229/229]  () {16 vars in 245 bytes} [Sat Apr  6 17:49:59 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 230/230] 73.65.198.207 () {34 vars in 807 bytes} [Sat Apr  6 17:50:58 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 231/231] 73.65.198.207 () {34 vars in 754 bytes} [Sat Apr  6 17:50:58 2024] GET /api/auth/refresh => generated 826 bytes in 140 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 233/232]  () {16 vars in 245 bytes} [Sat Apr  6 17:50:59 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 234/233] 73.65.198.207 () {34 vars in 759 bytes} [Sat Apr  6 17:51:07 2024] GET /api/household/1/tag => generated 3 bytes in 40 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 235/234] 73.65.198.207 () {34 vars in 751 bytes} [Sat Apr  6 17:51:23 2024] GET /api/household/1 => generated 687 bytes in 48 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 236/235] 73.65.198.207 () {34 vars in 751 bytes} [Sat Apr  6 17:51:23 2024] GET /api/household/1 => generated 687 bytes in 48 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 237/236] 73.65.198.207 () {34 vars in 759 bytes} [Sat Apr  6 17:51:23 2024] GET /api/household/1/tag => generated 3 bytes in 37 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 238/237] 73.65.198.207 () {34 vars in 765 bytes} [Sat Apr  6 17:51:24 2024] GET /api/household/1/recipe => generated 6402 bytes in 122 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 199)
[pid: 140|app: 0|req: 239/238] 73.65.198.207 () {34 vars in 759 bytes} [Sat Apr  6 17:51:26 2024] GET /api/household/1/tag => generated 3 bytes in 40 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 199)
[pid: 140|app: 0|req: 240/239]  () {16 vars in 245 bytes} [Sat Apr  6 17:52:00 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
[uwsgi-websocket] "GET /socket.io/?EIO=4&transport=websocket" (73.65.198.207) no PONG received in 3 seconds !!!
[pid: 140|app: 0|req: 240/240] 73.65.198.207 () {46 vars in 1030 bytes} [Sat Apr  6 17:50:59 2024] GET /socket.io/?EIO=4&transport=websocket => generated 134 bytes in 68081 msecs (HTTP/1.1 101) 4 headers in 164 bytes (2 switches on core 197)
[pid: 140|app: 0|req: 241/241]  () {16 vars in 245 bytes} [Sat Apr  6 17:53:00 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 242/242]  () {16 vars in 245 bytes} [Sat Apr  6 17:54:01 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 243/243]  () {16 vars in 245 bytes} [Sat Apr  6 17:55:01 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 244/244]  () {16 vars in 245 bytes} [Sat Apr  6 17:56:02 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 245/245]  () {16 vars in 245 bytes} [Sat Apr  6 17:57:02 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 246/246]  () {16 vars in 245 bytes} [Sat Apr  6 17:58:02 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 247/247]  () {16 vars in 245 bytes} [Sat Apr  6 17:59:03 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 248/248]  () {16 vars in 245 bytes} [Sat Apr  6 18:00:03 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 249/249]  () {16 vars in 245 bytes} [Sat Apr  6 18:01:04 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 250/250]  () {16 vars in 245 bytes} [Sat Apr  6 18:02:04 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 251/251]  () {16 vars in 245 bytes} [Sat Apr  6 18:03:05 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 252/252]  () {16 vars in 245 bytes} [Sat Apr  6 18:04:05 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 253/253]  () {16 vars in 245 bytes} [Sat Apr  6 18:05:06 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 254/254]  () {16 vars in 245 bytes} [Sat Apr  6 18:06:06 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 255/255]  () {16 vars in 245 bytes} [Sat Apr  6 18:07:06 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 256/256]  () {16 vars in 245 bytes} [Sat Apr  6 18:08:07 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 257/257]  () {16 vars in 245 bytes} [Sat Apr  6 18:09:07 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 258/258]  () {16 vars in 245 bytes} [Sat Apr  6 18:10:08 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 259/259]  () {16 vars in 245 bytes} [Sat Apr  6 18:11:09 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 260/260]  () {16 vars in 245 bytes} [Sat Apr  6 18:12:09 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 261/261]  () {16 vars in 245 bytes} [Sat Apr  6 18:13:10 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 262/262]  () {16 vars in 245 bytes} [Sat Apr  6 18:14:10 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 263/263] 10.0.0.243 () {44 vars in 2111 bytes} [Sat Apr  6 18:14:27 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 264/264] 10.0.0.243 () {44 vars in 2053 bytes} [Sat Apr  6 18:14:27 2024] GET /api/onboarding => generated 21 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 265/265] 10.0.0.243 () {50 vars in 2185 bytes} [Sat Apr  6 18:14:35 2024] POST /api/auth => generated 813 bytes in 883 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 266/266] 10.0.0.243 () {46 vars in 2466 bytes} [Sat Apr  6 18:14:35 2024] GET /socket.io/?EIO=4&transport=polling&t=luotzmzq => generated 97 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 100 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 267/267] 10.0.0.243 () {46 vars in 2393 bytes} [Sat Apr  6 18:14:35 2024] GET /api/user => generated 1087 bytes in 27 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 268/268] 10.0.0.243 () {52 vars in 2648 bytes} [Sat Apr  6 18:14:36 2024] POST /socket.io/?EIO=4&transport=polling&t=luotzn00&sid=iHBxMQH1g5pACb4tAAAS => generated 25 bytes in 0 msecs (HTTP/1.1 400) 1 headers in 54 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 270/269] 10.0.0.243 () {46 vars in 2407 bytes} [Sat Apr  6 18:14:36 2024] GET /api/household/1 => generated 687 bytes in 24 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 271/270] 10.0.0.243 () {46 vars in 2433 bytes} [Sat Apr  6 18:14:36 2024] GET /api/household/1/shoppinglist => generated 99 bytes in 19 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 272/271] 10.0.0.243 () {46 vars in 2415 bytes} [Sat Apr  6 18:14:36 2024] GET /api/household/1/tag => generated 3 bytes in 18 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 273/272] 10.0.0.243 () {46 vars in 2421 bytes} [Sat Apr  6 18:14:36 2024] GET /api/household/1/recipe => generated 6402 bytes in 46 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 274/273] 10.0.0.243 () {46 vars in 2423 bytes} [Sat Apr  6 18:14:36 2024] GET /api/household/1/planner => generated 3 bytes in 22 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 275/274] 10.0.0.243 () {46 vars in 2453 bytes} [Sat Apr  6 18:14:36 2024] GET /api/household/1/planner/recent-recipes => generated 3 bytes in 17 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 276/275] 10.0.0.243 () {46 vars in 2459 bytes} [Sat Apr  6 18:14:36 2024] GET /api/household/1/planner/suggested-recipes => generated 3 bytes in 18 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 277/276] 10.0.0.243 () {46 vars in 2462 bytes} [Sat Apr  6 18:14:36 2024] GET /api/household/1/expense/categories => generated 3 bytes in 17 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 278/277] 10.0.0.243 () {46 vars in 2453 bytes} [Sat Apr  6 18:14:36 2024] GET /api/household/1/expense?view=0 => generated 3 bytes in 18 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 279/278] 10.0.0.243 () {52 vars in 2665 bytes} [Sat Apr  6 18:14:36 2024] POST /socket.io/?EIO=4&transport=polling&t=luotzn20&sid=iHBxMQH1g5pACb4tAAAS => generated 25 bytes in 0 msecs (HTTP/1.1 400) 1 headers in 54 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 280/279] 10.0.0.243 () {46 vars in 2461 bytes} [Sat Apr  6 18:14:36 2024] GET /api/shoppinglist/1/items?orderby=0 => generated 1326 bytes in 35 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 281/280] 10.0.0.243 () {46 vars in 2442 bytes} [Sat Apr  6 18:14:36 2024] GET /api/household/1/category => generated 1666 bytes in 21 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 282/281] 10.0.0.243 () {46 vars in 2471 bytes} [Sat Apr  6 18:14:36 2024] GET /api/shoppinglist/1/recent-items?limit=9 => generated 3 bytes in 22 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 283/282] 10.0.0.243 () {46 vars in 2438 bytes} [Sat Apr  6 18:14:42 2024] GET /api/household/1/recipe => generated 6402 bytes in 122 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 284/283] 10.0.0.243 () {46 vars in 2432 bytes} [Sat Apr  6 18:14:42 2024] GET /api/household/1/tag => generated 3 bytes in 39 msecs (HTTP/1.1 200) 2 headers in 70 bytes (3 switches on core 197)
[pid: 140|app: 0|req: 285/284] 10.0.0.243 () {46 vars in 2424 bytes} [Sat Apr  6 18:14:42 2024] GET /api/household/1 => generated 687 bytes in 48 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 286/285] 10.0.0.243 () {46 vars in 2412 bytes} [Sat Apr  6 18:14:52 2024] GET /api/user => generated 1087 bytes in 50 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 198)
[pid: 140|app: 0|req: 286/286] 10.0.0.243 () {46 vars in 2516 bytes} [Sat Apr  6 18:14:36 2024] GET /socket.io/?EIO=4&transport=polling&t=luotzn00&sid=iHBxMQH1g5pACb4tAAAS => generated 1 bytes in 24978 msecs (HTTP/1.1 200) 2 headers in 100 bytes (3 switches on core 199)
[pid: 140|app: 0|req: 287/287]  () {16 vars in 245 bytes} [Sat Apr  6 18:15:10 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
[pid: 140|app: 0|req: 288/288] 10.0.0.243 () {52 vars in 2590 bytes} [Sat Apr  6 18:16:08 2024] POST /api/household/1/recipe/scrape => generated 1855 bytes in 996 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 199)
[pid: 140|app: 0|req: 289/289]  () {16 vars in 245 bytes} [Sat Apr  6 18:16:11 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
[pid: 140|app: 0|req: 290/290]  () {16 vars in 245 bytes} [Sat Apr  6 18:17:11 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 71 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)

**Comment by everything123** [comment]
https://www.aspicyperspective.com/best-homemade-salsa-recipe/

<img width="1422" alt="Screenshot 2024-04-06 at 7 29 54 PM" src="https://github.com/TomBursch/kitchenowl/assets/33844597/6982550d-b1b7-47bf-9165-2ed3f32808e0">

example: most of the ingredients arent adding in

**Comment by TomBursch** [comment]
Thanks for the report. Yes, I'm aware the ingredient detection is shit. I'm using a library for splitting something like `1 red onion` into `red onion` and `1` but it only works half the time.

I will close this issue in favor of https://github.com/TomBursch/kitchenowl/issues/163. The detection just needs a lot more work in general, and I think both issues are similar enough.
