### ISSUE TITLE
Bug: Recipe can't be added to Mealplaner on IOS app, if the recipe has no ingrediants

### ISSUE THREAD

**Issue by CaptainKey3s** [TomBursch/kitchenowl#431]
### Is this urgent?

Yes

### What parts are affected

Frontend

### What is the server version

v95

### What is the client version

4.2.1

### What platform are you using

iOS

### What's the problem 🤔

Recipe can't be added to mealplaner on the IOS app, if the recipe has no ingrediants.
It just shows the recipe name and no button.
Works on the android app.

**Comment by TomBursch** [comment]
Hi, thanks for the issue. I had some issues with my Mac setup, that is why the iOS app is one version behind. The new version is now in review by apple and should be published this week. The new version fixes this issue.
