### ISSUE TITLE
Feature request: Recipies grid view

### ISSUE THREAD

**Issue by yeKcim** [TomBursch/kitchenowl#452]
### What's the feature 🧐

This software is great, could be awesome, with a recipies grid view option

Exemple in gnome-recipies:

![Capture d’écran du 2024-05-22 14-12-34](https://github.com/TomBursch/kitchenowl/assets/10558744/e85a9f4b-1164-46d9-a7a5-036d35778231)

Thanks a lot for this soft

**Comment by TomBursch** [comment]
There exists a recipe grid view, if you click on the sorting at the top right of the recipes 😊

![Screenshot 2024-05-22 at 20-45-23 KitchenOwl](https://github.com/TomBursch/kitchenowl/assets/9092682/2600ad12-5075-4535-8410-a6debab1c92b)

**Comment by yeKcim** [comment]
Strange, I don't see sorting options

![Screenshot_20240523_073822](https://github.com/TomBursch/kitchenowl/assets/10558744/e36916fd-5b7e-4452-bacd-7c9cbe310bb4)

**Comment by yeKcim** [comment]
I just added one tag and now it's OK, thank you

**Comment by TomBursch** [comment]
Yeah, I think you've found a bug. It will be fixed in the next version.
