### ISSUE TITLE
Bug: mime types not provided in response headers

### ISSUE THREAD

**Issue by mpfl** [TomBursch/kitchenowl#477]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

96

### What is the client version

96

### What platform are you using

Web

### What's the problem 🤔

The kitchenowl docker image does not include the [media-types package](https://packages.debian.org/bookworm/media-types), which means that the HTTP response headers do not specify a MIME type for served files. This is a problem when using kitchenowl behind a reverse proxy that adds the `x-content-type-options: nosniff` header as it prevents the browser from inferring the MIME type by itself.

The end result is that HTML and Javascript files are treated as plain text and not rendered properly in-browser.

Manually adding the media-types package by running `apt install media-types` inside the container and restarting the container fixes the issue, but destroying and re-creating the container will make the issue arise again.

This should be resolvable by modifying the dockerfile to include the media-types package.

**Comment by Semoar** [comment]
Thanks for reporting and fixing the issue.

If someone else has the same problem: I worked around it with this nginx snippet:
```
location / {
  add_header Content-Type "text/html; charset=utf-8";
  proxy_pass http://localhost:8080;
}

location /api {
  proxy_pass http://localhost:8080;
}
```
