### ISSUE TITLE
Bug: sensitive cache data is stored in global /tmp with read access for everyone

### ISSUE THREAD

**Issue by kloenk** [TomBursch/kitchenowl#479]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

0.5.2

### What is the client version

0.5.2

### What platform are you using

Linux

### What's the problem 🤔

The kitchenowl desktop client stores cache data in the global folder `/tmp/kitchenowl`. Accessible to everyone. This includes names of who is in a household and the spending limits.

**Comment by TomBursch** [comment]
I guess `XDG_CACHE_HOME` would be a better place.
