### ISSUE TITLE
Feature request: Environment Variable to Control Usage of Default Ingredients

### ISSUE THREAD

**Issue by ajuancer** [TomBursch/kitchenowl#482]
### What's the feature 🧐

Hi there!

I propose the following feature:

## Summary
Introduce an environment variable to toggle default ingredients in the application. This boolean variable will determine whether the application should use pre-defined default ingredients.

## Background
Currently, the app uses a set of default ingredients when the user specifies none. This is beneficial for users who want quick and easy access to predefined ingredients. However, some users might prefer to specify their ingredients without any defaults being applied. To provide flexibility and improve user control, i propose the addition of an environment variable to enable or disable the use of default ingredients.

## Proposed Solution
* Environment Variable Definition:
    * Name: `USE_DEFAULT_INGREDIENTS`
    * Type: Boolean
    * Default Value: `True` (to maintain current behaviour)

**Comment by TomBursch** [comment]
When you create a household, you can set its language to `None`. It doesn't change anything other than not importing any default items. 

> Currently, the app uses a set of default ingredients when the user specifies none

Or am I misunderstanding you, and you did that, but still had default items? Then I would consider this a bug.

**Comment by ajuancer** [comment]
Hi Tom! You're right, I didn't select `any language` when configuring the household. Your proposal does indeed work, thank you!
