### ISSUE TITLE
Bug: Recipe ingredients do not get deselected once you press the "Add Ingredients" button

### ISSUE THREAD

**Issue by aero31aero** [TomBursch/kitchenowl#511]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

v97

### What is the client version

v0.5.2(97)

### What platform are you using

Android

### What's the problem 🤔

When I go to a "recipe" and then select some ingredients, I see the "Add {x} ingredients" button.

If I click that button, sometimes the animation etc is super quick and I'm not sure if I actually tapped the button or not. I end up trying again and double-adding the ingredients.

Expected behavior: on successfully tapping the button, deselect all the items I just added to my shopping list and hide the "add ingredients" button.

**Comment by TomBursch** [comment]
Great idea! Maybe a little animation, where all items pop/"jump" a little, would be nice too.

**Comment by Demjoo** [comment]
Hello @TomBursch , I would like to work on this issue. Can you please assing it to me and maybe share your vision?

**Comment by TomBursch** [comment]
@Demjoo Hey, sure! Thanks for wanting to help. The first part should be easy enough. In [this method](https://github.com/TomBursch/kitchenowl/blob/20a178450dade2dc5af65881c16310e0c5531fbd/kitchenowl/lib/cubits/recipe_cubit.dart#L80) the state needs to be copied and emitted with the selected items set back to the recipe mandatory ones.

About the animation I'm not sure yet how to implement it. But I'm thinking of something where all items are moved vertically in a wave like motion starting from the bottom. But I'm open to suggestions. You can also start with the first part and do two PRs for it. If you need help (e.g. with setup) feel free to pm me on matrix.

Edit: I've just reread the initial issue. We could also deselect all items. But I don't think it'd be good to hide the add items button.

**Comment by TomBursch** [comment]
Closed by #537
