### ISSUE TITLE
Feature request: A unique user agent for the app

### ISSUE THREAD

**Issue by DanteMS** [TomBursch/kitchenowl#514]
### What's the feature 🧐

A unique user agent for the app. For example, `KitchenOwl-android/0.5.2`. The user agent it uses for now is `Dart/3.4 (dart:io)`.
A possible use case: on my server I'm using a user agent-based redirection, so users wouldn't have to remember which subdomain to use for which app.

**Comment by TomBursch** [comment]
The new user agent will be, as you suggested, `KitchenOwl-platform/version`.

**Comment by DanteMS** [comment]
Thanks for implementing this!
However, some paths, like images, still have the old user agent:
```
"GET /api/upload/97660742-fa3d-4ca6-8d6c-ee76eafb534a.png HTTP/1.1" 304 0 "-" "Dart/3.6 (dart:io)"
"GET /socket.io/?EIO=4&transport=websocket HTTP/1.1" 101 145 "-" "Dart/3.6 (dart:io)"
```
