### ISSUE TITLE
Feature request: Fridge inventory

### ISSUE THREAD

**Issue by HaWaKv78** [TomBursch/kitchenowl#517]
### What's the feature 🧐

It would be nice to be able to keep an inventory of the items in my fridge. I'm using a shopping list now to do this but I only can add ingridients, it would be nice to also be able to store recepies and the ammount of portions next to ingridients, all together in one list

**Comment by TomBursch** [comment]
Thanks for the feature request! I'll close this, since https://github.com/TomBursch/kitchenowl/issues/10 is very similar.
