### ISSUE TITLE
Feature request: Adding prep and cook times

### ISSUE THREAD

**Issue by eclairevoyant** [TomBursch/kitchenowl#52]
### What's the feature 🧐

I'm proposing adding preparation and cooking time fields to each recipe. Most recipes online or in books have prep, cook, and total time - this would be helpful information for planning out my time both in and out of the kitchen, and the scraper library already supports these fields.

Some recipes may have other types of times (e.g. dough recipes often mention proofing times, additionally) but I think adding just these two times should be sufficient for most use cases.

I can go ahead with making PRs (still WIP at the moment) for this, both here and in the backend repo if you agree that this is valuable for the app.

**Comment by TomBursch** [comment]
> Some recipes may have other types of times (e.g. dough recipes often mention proofing times, additionally) but I think adding just these two times should be sufficient for most use cases.

So have 3 editable times in total (prep, cook, total) or just two (prep, cook) and total is the sum. I think I prefer the latter, what about you?

You can create a PR (even an unfinished one and I'll complete it) or I'll implement it myself when I'm adding servings :)

**Comment by eclairevoyant** [comment]
I was considering the former because this is how I envision the 3 times:
prep = time spent actively working before cooking/baking
cook = time spent on stove or in oven or some externally powered appliance
total = time spent in total from start to finish

For example, for recipes involving heating up meat, the total time will include waiting at the end for the meat to cool slightly before cutting in.
For breads, this will involve waiting for dough to proof as well as waiting at the end before cutting in.
For items involving fermentation or drying, there would be waiting there as well, but I wouldn't consider this active prep work, nor would it be cook time unless we are using a powered dehydrator perhaps?
etc.

Either way thanks for being open to this; I'll send along a PR when I get a chance.
