### ISSUE TITLE
Feature request: Recipe Instructions, Recipe Notes, and Nutrition fields

### ISSUE THREAD

**Issue by MyHeadHurtsNow** [TomBursch/kitchenowl#535]
### What's the feature 🧐

Recipe managers usually include fields that allow users to store:
- the cooking instructions for each recipe;
- Recipe Notes where one can add things like variations and storage instructions;
- Nutritional Information field to add nutritional macros.

Without these, one will have to use a seperate recipe manager.

I note that this is a beta version, so I hope you'll include these in your next release, as well as update the User Documentation, which is not really helpful right now. So far, I like the direction you're taking. But the web page capture doesn't work on pages that Broccoli captured, and editing mistakes isn't intuitive. Nevertheless, fix these wrinkles, and it could very well compete with (or even surpass) my favourite Paprika. Good luck on your journey.

**Comment by TomBursch** [comment]
Hi, thanks for the feature request! You can use the description field for most of what you requested. It supports [Markdown](https://docs.kitchenowl.org/latest/Tips-%26-Tricks/markdown/).

There are individual issues for what you requested: #259 #206
Hence, I'll close this issue. Feel free to provide additional information requests in those 🙂
