### ISSUE TITLE
Bug: F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [TomBursch/kitchenowl#552]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

 None

### What is the client version

0.6.3

### What platform are you using

Android

### What's the problem 🤔

https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8455337719 Could you please take a look? Thanks!

**Comment by TomBursch** [comment]
Thanks for making me aware. I've fixed the build and published a new tag.

**Comment by linsui** [comment]
Thanks!
