### ISSUE TITLE
Recipe scrape timeout too short when using ollama LLM on my setup

### ISSUE THREAD

**Issue by zergar** [TomBursch/kitchenowl#556]
Hei,

Thanks for the new 0.6.3 release and KitchenOwl in general. I'm using it alot. 

Unfortunately, I ran into a timeout with the new recipe LLM scraping functionality as my ollama deployment is not backed by a strong enough server to respond to the request within 15 seconds, as required by https://github.com/TomBursch/kitchenowl/blob/5686cfe5e553c2f3fa9fa18ed9626facf3b47986/kitchenowl/lib/services/api/recipe.dart#L12 .This means I cannot use this new feature. Actually, when looking at the Network Debugger in my browser, I can see the Log message mentioning the timeout after 15 seconds, and the request completing sucessfully after 17 seconds.

I can imagine a couple of solutions for this issue:

1. Have the scraping timeout defined by a frontend ENV var from the server side
2. Have the scraping timeout defined by a settings parameter in the UI itself
3. Display an error message akin to "this takes longer than expected. Do you want to abort?" after 15 seconds, and then if the request succeeds later than expected, display the successful scrape.
4. Increasing the timeout like in #454 would also work, but I would deem this a a worse solution since the timeout can be very setup-specific.

Thanks!

**Comment by TomBursch** [comment]
Thanks for the issue, I think your third solution is a good one. I increased the timeout to 5 minutes, but displaying a message after 15 seconds.
