### ISSUE TITLE
Bug: New recipe tags are not shown in recipe list immediately

### ISSUE THREAD

**Issue by schnillerman** [TomBursch/kitchenowl#557]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

v101

### What is the client version

0.6.3

### What platform are you using

Android

### What's the problem 🤔

After saving a recipe with new tags, the tags are not shown on top of the recipe list unless switching to shopping list and back. 

![Screenshot_20241125_011316](https://github.com/user-attachments/assets/c3a3f185-d1cb-4e15-aad5-3ce726ce3ed1)

**Comment by TomBursch** [comment]
Strange I cannot reproduce this and the code looks correct too. Can you remember if there is something specific you did before this happened (like creating multiple recipes)?

**Comment by schnillerman** [comment]
Not really :/ I just tried it again and everything was fine. Maybe it was a sync issue.
