### ISSUE TITLE
Bug: Issue loading page

### ISSUE THREAD

**Issue by jfdid** [TomBursch/kitchenowl#58]
### Is this urgent?

Yes

### What parts are affected

Frontend

### What are the Server/Client versions of KitchenOwl

0.3.2

### What's the problem 🤔

Using docker-compose, accessing frontend from web browser on another PC, getting the following error when trying to load main.dart.js:31883:
Failed to load resource: net::ERR_CONNECTION_REFUSED localhost:9091/api/h…LBfkkV7ctWwgibW6V:1 
I'm not a programmer but all the other GET requests are directed to the URL 192.168.7.77 except this one.  This one defaults to localhost and can't be accessed.  I tried from 3 different browsers.
Once I updated the docker-compose URL's from localhost to 192.168.7.77, it worked fine from external browsers.  When accessed from browser on the server, it then had to be accessed from the 190.168.7.77 url rather than localhost or 0.0.0.0.
Firefox says it's a Cross-Origin Request Blocked: The same origin policy disallows reading the remote resource at http://localhost.....

Let me know if you need more info - I'm on a time crunch and think you may know what this is without more info.

**Comment by TomBursch** [comment]
This error only occurs when you haven't setup the `FRONT_URL` correctly inside your configuration.
See https://tombursch.github.io/kitchenowl/get-started/
The `FRONT_URL` should exactly match what you would type into the URL bar of your browser and needs to be set on both the backend and the frontend

Edit: This includes the schema so `https` if you're using ssl

**Comment by jfdid** [comment]
Thanks Tom, I did end up changing the FRONT_URL to 192.168.7.77 rather than localhost and it works.
I'm not sure how big of a deal it is to fix this bug, but for a lot of people, the error may cause issues as they assume localhost is the same as the host's IP(192.168.7.77 in my case) or 0.0.0.0.  I know I troubleshot it for quite some time before realizing it would ONLY work with the IP address(even from the host machine).
Further, if I had localhost as the FRONT_URL, I could reach the frontend from another PC via the IP address, but got the connect to server error, which is the same issue, but still confusing.
If it's not something you can easily fix, may I recommend adding a clear comment in the docker-compose.yml example file?
NOTE: I don't see the error on the Fdroid Android App.

**Comment by TomBursch** [comment]
I know it's a bit confusing to setup, the linked issue/PR will fix that

**Comment by TomBursch** [comment]
I just published a new stable release that gets rid of the `FRONT_URL` variable. This should fix everybody's problems related to that.
See https://tombursch.github.io/kitchenowl/get-started/ for the updated/simplified guide.
