### ISSUE TITLE
Bug: Deleting a household while others are logged in does not evict them

### ISSUE THREAD

**Issue by RedX2501** [TomBursch/kitchenowl#585]
### Is this urgent?

No

### What parts are affected

Both

### What is the server version

dev

### What is the client version

dev

### What platform are you using

Android, Web, Linux

### What's the problem 🤔

When you delete a household the other logged in users are not "evicted". They can even continue adding items to shopping lists without any errors.

But when they try to change household they obviously cannot return to their original house and all their work is lost.

All current users of the household should receive a message and be forced to change the household immediately.

**Comment by TomBursch** [comment]
Deleting a household only soft deletes them (removing all members) and once a month, a job deletes all empty households.
If you test this as a server admin, access rules don't apply and the server will allow you to edit deleted households. But normal users won't be able to. They are not kicked out of the household though and can change it locally (which needs fixing) but they cannot edit anything on the server.
