### ISSUE TITLE
Bug: Docker container (via compose) is inaccessible from server

### ISSUE THREAD

**Issue by dei-layborer** [TomBursch/kitchenowl#589]
### Is this urgent?

No

### What parts are affected

Both

### What is the server version

0.6.4

### What is the client version

0.6.4

### What platform are you using

Linux

### What's the problem 🤔

The docker container does not currently work properly.

I used the ``docker-compose.yml`` file linked from [the docs](https://docs.kitchenowl.org/latest/self-hosting/), only changing the ports to ``8080:80`` since I plan to use a subdomain.  ``docker-compose`` reports that the front- and back-end containers are up and healthy.

However, ``localhost:8080`` is inaccessible.  For example, running ``curl localhost:8080`` from my server just hangs until I kill it, as does ``curl [server ip]:8080``.  Meanwhile, nginx returns ``504 Gateway Timeout`` when trying to reach the subdomain that is proxied (to, again, ``http://localhost:8080``).

The only thing that *does* work is ``http://[domain]:8080``.  But the docker container being inaccessible from ``localhost`` means I can't use SSL or a subdomain.  I've tried stopping ``iptables`` to see if that was the issue, but the behavior doesn't change.  FWIW, I've used both the example nginx config [from the docs](https://docs.kitchenowl.org/latest/self-hosting/reverse-proxy/#nginx) as well as what's generated by certbot (replacing the "location" with ``proxy_pass``), and this too does not change anything.  The fact that the site is inaccessible from the server itself seems to suggest it's a problem with docker or the container.

Please let me know what if any information would be helpful.

**Comment by TomBursch** [comment]
Strange. Do you have anything special set up with docker or your firewall? Because the curl command should definitely work. Even more so since `http://[domain]:8080` works.

**Comment by dei-layborer** [comment]
Thanks for following up!  And "strange" is definitely right.

I don't know what "special" would mean in this context, though.  Docker and docker-compose were freshly installed just before working on this, and no changes were made to any of their configs.  Meanwhile I don't think it's a firewall issue...as I mentioned, even stopping ``iptables`` altogether doesn't change anything.

**Comment by TomBursch** [comment]
Can you try the all-in-one container? Do you have this issue with other containers too?

**Comment by dei-layborer** [comment]
I haven't tried any other containers on this VPS, so not sure there.

With the all-in-one, I had to change the ``ports`` entry from "80:8080" to "8080:80".  The first one doesn't work, as I get an error that ``tcp4 0.0.0.0:80`` is already in use (presumably by nginx).

But with that change, I get a ``502 bad gateway`` error when trying to go to the subdomain.  Running ``curl localhost:8080`` from my VPS gives the following error: ``curl: (56) Recv failure: Connection reset by peer``.  ``docker-compose ps`` shows the container as up and healthy, meanwhile.

**Comment by NilsKrause** [comment]
For what's it worth, I am currently running the newest version of kitchenowl on a vps, behind a nginx reverse proxy, accessible via a  subdomain and everything seems to be working fine. I am running the[ compose from the repo](https://github.com/TomBursch/kitchenowl/blob/31c54860fb2135953ee34f2f113020824d67119a/docker-compose.yml) 1:1 with just the exposed port changed.

Access via web/app and curl on host are working. Sounds like there is something going on with your setup?

I would suggest just setting the exposed port of your container to some random port and also changing the proxy_pass in your nginx instance to that port and trying again.
Like so for example:

docker-compose.yml
``` docker-compose.yml
[...]
front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    # environment:
    #   - BACK_URL=back:5000 # Change this if you rename the containers
    ports:
      - "7213:80"
    depends_on:
      - back
[...]
```

nginx config
```nginx config
[...]
location / {
        proxy_pass http://localhost:7213;
}
[...]
```

**Comment by dei-layborer** [comment]
I appreciate the suggestion, but this unfortunately did not have any effect.

Is there any way to narrow down the problem?

**Comment by NilsKrause** [comment]
Only thing I can think of is that the docker network is, somehow, not correctly attached to your host. 

You maybe also could have a look at the logs while you try to connect to it.

```
docker logs -f <id of container>
```

But other than that, I am out of ideas.

**Comment by dei-layborer** [comment]
Trying the original compose file (i.e. not the all-in-one), here are the logs.

For the front-end:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/01-kitchenowl-customization.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/12/20 14:41:39 [notice] 1#1: using the "epoll" event method
2024/12/20 14:41:39 [notice] 1#1: nginx/1.26.2
2024/12/20 14:41:39 [notice] 1#1: built by gcc 13.2.1 20240309 (Alpine 13.2.1_git20240309)
2024/12/20 14:41:39 [notice] 1#1: OS: Linux 6.1.0-28-amd64
2024/12/20 14:41:39 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/12/20 14:41:39 [notice] 1#1: start worker processes
2024/12/20 14:41:39 [notice] 1#1: start worker process 38
127.0.0.1 - - [20/Dec/2024:14:42:09 +0000] "GET / HTTP/1.1" 200 2708 "-" "curl/8.11.0" "-"
127.0.0.1 - - [20/Dec/2024:14:42:39 +0000] "GET / HTTP/1.1" 200 2708 "-" "curl/8.11.0" "-"
127.0.0.1 - - [20/Dec/2024:14:43:09 +0000] "GET / HTTP/1.1" 200 2708 "-" "curl/8.11.0" "-"
```

Of note, those last three entries appeared as soon as the log was displayed, and there were no new entries when trying to reach the subdomain/container.

For the back-end:

```
/opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:344: SyntaxWarning: invalid escape sequence '\-'
  """Parses a quoted string.
/opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:355: SyntaxWarning: invalid escape sequence '\-'
  """Parses a token or a quoted-string.
/opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:518: SyntaxWarning: invalid escape sequence '\-'
  """Parses a ()-style comment from a header value.
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
  return current_app.extensions['migrate'].db.get_engine()
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
  return current_app.extensions['migrate'].db.get_engine()
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Upgrading households: 0it [00:00, ?it/s]
[uWSGI] getting INI configuration from wsgi.ini
*** Starting uWSGI 2.0.28 (64bit) on [Fri Dec 20 14:41:55 2024] ***
compiled with version: 12.2.0 on 24 November 2024 16:15:34
os: Linux-6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22)
nodename: c0ec08573d96
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /usr/src/kitchenowl
detected binary path: /opt/venv/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
- async cores set to 200 - fd table size: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP6 address [::]:5000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.12.7 (main, Nov 12 2024, 02:26:49) [GCC 12.2.0]
Python main interpreter initialized at 0x7f62510e6930
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 4307328 bytes (4206 KB) for 200 cores
*** Operational MODE: async ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
spawned uWSGI master process (pid: 15)
spawned uWSGI worker 1 (pid: 16, cores: 200)
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x7f62510e6930 pid: 16 (default app)
*** running gevent loop engine [addr:0x5604dc011bb0] ***
[pid: 16|app: 0|req: 1/1]  () {16 vars in 245 bytes} [Fri Dec 20 14:42:38 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 72 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
[pid: 16|app: 0|req: 2/2]  () {16 vars in 245 bytes} [Fri Dec 20 14:43:38 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 72 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
[pid: 16|app: 0|req: 3/3]  () {16 vars in 245 bytes} [Fri Dec 20 14:44:38 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 72 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
[pid: 16|app: 0|req: 4/4]  () {16 vars in 245 bytes} [Fri Dec 20 14:45:38 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 72 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
[pid: 16|app: 0|req: 5/5]  () {16 vars in 245 bytes} [Fri Dec 20 14:46:39 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 72 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
[pid: 16|app: 0|req: 6/6]  () {16 vars in 245 bytes} [Fri Dec 20 14:47:39 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 72 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
```

When I go went to the subdomain in a browser, a single line was added:

```
[pid: 16|app: 0|req: 7/7]  () {16 vars in 245 bytes} [Fri Dec 20 14:48:39 2024] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 72 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 199)
```

Does this suggest anything?

**Comment by NilsKrause** [comment]
Yeah, the last line added was simply the healthcheck to check if the app is running correctly. The logs look good as far as for kitchenowl.

It seems that your requests are not reaching the application inside the container.

There _might be_ something not correctly setup in on your host/docker. If you have other containers running and are able to reach them fine, you need to make sure that the container is connected to the docker bridge network.
If kitchenowl is the only container running on the host (or other containers have the same problem), then you maybe need to check if the bridge network of docker is setup correctly. Have a look at those links and maybe have a look around the interwebs for similar problems with your os/docker version configuration:

- https://docs.docker.com/engine/network/drivers/bridge/
- https://forums.docker.com/t/docker-bridge-networking-does-not-work-in-ubuntu-22-04/136326/10

All in all  I am very confident that is has nothing to do with kitchenowl itself.

**Comment by dei-layborer** [comment]
Makes sense, and I appreciate your help with troubleshooting this.

**Comment by dei-layborer** [comment]
@TomBursch 

I hope you'll excuse the ping, but I wanted to update this briefly.  At the suggestion of someone on reddit, I ran ``curl -v`` both locally and on the subdomain.

``curl -v localhost:[port]``:

```
*   Trying 127.0.0.1:5874...
* Connected to localhost (127.0.0.1) port 5874 (#0)
> GET / HTTP/1.1
> Host: localhost:5874
> User-Agent: curl/7.88.1
> Accept: */*
>
```

(After that it just sits there.)

``curl -v https://[subdomain.domain.com]``:

```
*   Trying [IP]...
* Connected to [subdomain & IP] port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=[subdomain.domain.com]
*  start date: Dec 18 18:17:22 2024 GMT
*  expire date: Mar 18 18:17:21 2025 GMT
*  subjectAltName: host "[subdomain.domain.com]" matched cert's "[subdomain.domain.com]"
*  issuer: C=US; O=Let's Encrypt; CN=E6
*  SSL certificate verify ok.
* using HTTP/1.1
> GET / HTTP/1.1
> Host: [subdomain.domain.com]
> User-Agent: curl/7.88.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 504 Gateway Time-out
< Server: nginx/1.22.1
< Date: Fri, 20 Dec 2024 18:23:13 GMT
< Content-Type: text/html
< Content-Length: 167
< Connection: keep-alive
<
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.22.1</center>
</body>
</html>
* Connection #0 to host [subdomain.domain.com] left intact
```

I don't know if this suggests anything to you (and you've already given me more than enough time), but figured it wouldn't hurt to check...

**Comment by TomBursch** [comment]
No worries about the ping. Thanks @NilsKrause for helping out. 
I agree with Nils, the KitchenOwl logs look fine and you should definitely try another container and see if it works. The curl logs are expected and look normal, since nginx has a timeout and curl itself not.

**Comment by dei-layborer** [comment]
Gotcha.  I did try a different docker image on the same port just to confirm, and got the same results (bad gateway timeout).  (And I didn't doubt y'all's diagnosis, to be clear.)

I'm not sure how to even begin troubleshooting this, though.  Docker's documentation is useless in that regard, unfortunately.

Is there any way to self host without using docker?
