### ISSUE TITLE
Web Docker: main.dart.js

### ISSUE THREAD

**Issue by DieterKoblenz** [TomBursch/kitchenowl#6]
main.dart.js:4015 Uncaught TypeError: null: type 'minified:vf' is not a subtype of type 'String'

I'm getting a blank screen when I try to load the web application.

**Comment by DieterKoblenz** [comment]
I'm assuming you also included this fix in the docker image? I just deleted the container, and started it again. I'm still getting this error:

`Uncaught TypeError: null: type 'minified:vf' is not a subtype of type 'String'
    at Object.c (main.dart.js:4015:3)
    at Object.aRA (main.dart.js:4630:18)
    at kj.b5W [as a] (main.dart.js:4625:3)
    at Object.cK (main.dart.js:5244:25)
    at Object.b85 (main.dart.js:26871:26)
    at main.dart.js:26892:14
    at aFj.a (main.dart.js:5201:62)
    at aFj.$2 (main.dart.js:39419:14)
    at aE2.$1 (main.dart.js:39413:21)
    at a2s.oI (main.dart.js:40482:31)`

**Comment by TomBursch** [comment]
Did you pull the latest image again?
```
docker pull tombursch/kitchenowl-web
```
This should be fixed. There seems to be a bug in one of the dependencies.

**Comment by DieterKoblenz** [comment]
Yeah, I did:

`latest: Pulling from tombursch/kitchenowl-web
Digest: sha256:863d9416ce0dfb0b5882a9197e2e420d44ce7b0e996ca86840490df5086d0131
Status: Image is up to date for tombursch/kitchenowl-web:latest
`

**Comment by TomBursch** [comment]
Hmm strange, it works for me. Are you sure you're using this version for the container? 
What does is say at KitchenOwl when running `docker container ls`?

**Comment by DieterKoblenz** [comment]
`d1af58f1863d   tombursch/kitchenowl-web:latest              "./entrypoint.sh"        8 hours ago     Up 8 hours              0.0.0.0:7411->80/tcp                                                                         KitchenOwlWeb
5788fb8d79e0   tombursch/kitchenowl                         "./entrypoint.sh"        20 hours ago    Up 9 hours (healthy)    0.0.0.0:7410->5000/tcp                                                                       KitchenOwl
`

**Comment by TomBursch** [comment]
So I just tried it again with the docker image and I definitely don't have that issue anymore. I'm sorry that you're facing this issue.
Could you try to run `docker container inspect d1af58f1863d | grep Image`?
The output should be:
```
        "Image": "sha256:f4265cca1ec2da952f34c4103b949de8cefce4b4500b102b06cea74a7ed2fa02",
            "Image": "tombursch/kitchenowl-web:latest",
```
If not I'll reopen this issue and do some further investigation what the problem could be.

**Comment by DieterKoblenz** [comment]
Yeah this is the output:
`        "Image": "sha256:f4265cca1ec2da952f34c4103b949de8cefce4b4500b102b06cea74a7ed2fa02",
            "Image": "tombursch/kitchenowl-web:latest",
`

I'll try it on a different machine too with compose.

**Comment by TomBursch** [comment]
Accidentally deleted my comment. 
Hmm really strange I'll reopen the issue.

**Comment by TomBursch** [comment]
Did you get a chance to try it on another system yet? What browser are you using?

**Comment by DieterKoblenz** [comment]
I'm using Chrome (97), the web docker is working on the second machine. 

I'll try to figure out what is wrong with my regular setup.
