### ISSUE TITLE
Feature request: ability to change size of icons/buttons

### ISSUE THREAD

**Issue by jfdid** [TomBursch/kitchenowl#60]
### What's the feature 🧐

On me and my wife's phones, the squircle icons are pretty large and could be condensed vertically in order to see more of the list.  It's definitely not a deal breaker but sometimes we have large lists and it's nice to be able to see a little more on the screen.

Possibly a selector in the settings to choose small, medium, large?

**Comment by TomBursch** [comment]
Edit: that response was supposed to be on another issue.
