### ISSUE TITLE
Bug: 0.6.5+ failes to load (Docker AIO)

### ISSUE THREAD

**Issue by siimpliidiip** [TomBursch/kitchenowl#602]
### Is this urgent?

No

### What parts are affected

Both

### What is the server version

v 0.6.5 , 0.6.6, 0.6.7

### What is the client version

any

### What platform are you using

Web, Linux

### What's the problem 🤔

Using the docker version.
I keep getting errors in my log and it fails to load.
Works fine if downgraded to 0.6.4
```
/opt/venv/bin/flask: 3: import: not found
/opt/venv/bin/flask: 4: import: not found
/opt/venv/bin/flask: 5: from: not found
/opt/venv/bin/flask: 7: Syntax error: "(" unexpected (expecting "then")
```

### Share your logs

```Shell
/opt/venv/bin/flask: 3: import: not found
/opt/venv/bin/flask: 4: import: not found
/opt/venv/bin/flask: 5: from: not found
/opt/venv/bin/flask: 7: Syntax error: "(" unexpected (expecting "then")
```
```


### Share your configuration

```
KitchenOwl:
    container_name: KitchenOwl
    hostname: KitchenOwl
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    ports:
      - 8030:8080
    environment:
      - JWT_SECRET_KEY=xxxxxxxx
    volumes:
      - KitchenOwl_data:/data
```

**Comment by TomBursch** [comment]
Is this a duplicate of #599? Your logs look a bit strange. Can you report if this still happens in v0.6.8?

**Comment by siimpliidiip** [comment]
I had a look at #599 before creating a new one, as in my case the apps didn't work either. 
Also like you said, I had a loop of the flask errors over and over which seemed odd.

v0.6.8 has fixed it though. Back to working order.
