### ISSUE TITLE
Feature request: double tap to remove item from grocery list

### ISSUE THREAD

**Issue by jfdid** [TomBursch/kitchenowl#61]
### What's the feature 🧐

It's easy to tap an item on the grocery list, removing it by mistake(child reaches to grab the phone, etc).  
Would it be possible to have the choice of double-clicking the item to remove it from the list, rather than a single click?

**Comment by freerafiki** [comment]
We also started using the app and we strongly agree - a different way to remove and re-add the items would be great, thanks!

**Comment by irishrain** [comment]
I agree that this is an issue, but I'm unsure double tapping is the right solution. I started #92 to discuss improvement ideas, maybe you want to join the discussion?

**Comment by freerafiki** [comment]
Yes, will join in there. Thanks for the effort!

**Comment by TomBursch** [comment]
Superseded by #209 
In the settings, you will be able to select if items are removed on tap, or after you press a confirm button (fab).
