### ISSUE TITLE
Issue loading page

### ISSUE THREAD

**Issue by JaswinderJohal** [TomBursch/kitchenowl#63]
When i run docket compose it creates instances and all looks good till i go to url and i get message stating "Hmmmm.. couldn't reach server" and nothing changes if refresh page.

**Comment by TomBursch** [comment]
Its most likely the same as #58
I know it's not obvious right now but it will be easier in the next version

**Comment by Rygorazd** [comment]
Have exactly same problem & error message, however connecting via app & creating user account works fine. Looks like browser issue?
![image](https://user-images.githubusercontent.com/32866806/195790665-2780bafa-f955-453a-8007-1c1c84898971.png)

**Comment by TomBursch** [comment]
No, like I mentioned in the other issue this is most likely an issue with your setup. The `FRONT_URL` environment variables have to exactly match the URL you type into your browser. I'm working on getting rid of that env variable.

**Comment by jfdid** [comment]
> Have exactly same problem & error message, however connecting via app & creating user account works fine. Looks like browser issue? ![image](https://user-images.githubusercontent.com/32866806/195790665-2780bafa-f955-453a-8007-1c1c84898971.png)

I had the same symptoms - could connect via the app, but not a browser.  Per Tom's answer - I got around it by changing FRONT_URL from "localhost" to the actual machine's IP address and using that address to access the front end(not localhost:5000).

**Comment by Rygorazd** [comment]
> > Have exactly same problem & error message, however connecting via app & creating user account works fine. Looks like browser issue? ![image](https://user-images.githubusercontent.com/32866806/195790665-2780bafa-f955-453a-8007-1c1c84898971.png)
> 
> I had the same symptoms - could connect via the app, but not a browser. Per Tom's answer - I got around it by changing FRONT_URL and BACK_URL from "localhost" to the actual machine's IP address and using that address to access the front end(not localhost:5000).

I'm using only app to access the content so it's fine for now. thx

**Comment by TomBursch** [comment]
@jfdid did you change the `BACK_URL` as well? That shouldn't be needed as the default is using docker's internal networking capabilites and should probably only be edited if you're not using docker compose or the backend is on another server.

**Comment by jfdid** [comment]
> 

I just checked, and no, I didn't change BACK_URL.  I edited my post above - thanks Tom.

**Comment by TomBursch** [comment]
I also want to add that the schema in `FRONT_URL` has to be correct as well. So `https://mydomain.com` instead of `http://mydomain.com`

**Comment by TomBursch** [comment]
I just published a new stable release that gets rid of the `FRONT_URL` variable. This should fix everybody's problems related to that.
See https://tombursch.github.io/kitchenowl/get-started/ for the updated/simplified guide.
