### ISSUE TITLE
Bug: Unable to login

### ISSUE THREAD

**Issue by Rygorazd** [TomBursch/kitchenowl#68]
### Is this urgent?

Yes

### What parts are affected

Both

### What are the Server/Client versions of KitchenOwl

letest

### What's the problem 🤔

After creating new user in mobile app I'm unable to login - credentials are correct, the screen cycles to default login page. Can't find anything in the backend or frontend logs

**Comment by TomBursch** [comment]
There is currently no info whether your credentials were correct. So cycling between the login page you entered either the wrong password or wrong username.

**Comment by Rygorazd** [comment]
Thanks, but is there a way of resetting the password? Or creating new user? I can't login via web page (see #16)

**Comment by TomBursch** [comment]
The web page has the same functionality as the app, currently there is no way to reset a password. But you gave me the idea to write a small console script to do that in the future. The best solution is to manually delete all users which would bring the app back to the onboarding process while also retaining all information. That is a bit technical but I can give some instructions if you want to give it a shot. Or reset your instance if you don't have anything valuable saved yet.

**Comment by Rygorazd** [comment]
Looks like I need to remove the containers and app from the phone to revert to new users settings?

**Comment by TomBursch** [comment]
To reset all settings (including saved recipes, expenses, and items) you simply remove the docker volume and recreate the stack. You can keep the app installed on your phone. So first find out which the docker volume is by typing `docker volume ls` and then `docker volume rm KITCHENOWL_VOLUME_NAME`.

**Comment by Rygorazd** [comment]
Out of curiosity, how many users can we have in one instance?
I have removed the docker & storage, spinned new instance, on my mobile I was able to create new user & login but on another device this option was not present - only login with existing user. Looks like the device info is saved somewhere?

**Comment by TomBursch** [comment]
You can have as many users as you want. You can create new users in the server settings when logged in. I.e. profile -> Server -> tap plus next to users to create a new one.
Or did I misunderstand your question?

**Comment by Rygorazd** [comment]
That's exactly what I meant :) thank you, I missed this option to create the user from within the app.

**Comment by LuVar** [comment]
Just in case, you want to reset password for your KitchenOwl installation when backend is running in your own and accessible docker:

```
docker volume ls
docker volume inspect kitchenowl_kitchenowl_data
sudo mc /var/lib/docker/volumes/kitchenowl_kitchenowl_data/_data
sqlite3 database.db

//show current password hashes. To "decode" string, have a look at https://en.wikipedia.org/wiki/Bcrypt#Description
select * from user;

//to set passwords for all users to "lolo"
update user set password = '$2a$14$DBc2epl.xg2krnNovB3M9O/jyqndE13d./KQIxBn/5mFBleluz/I2';
```
