### ISSUE TITLE
Feature request: Parsing of ingredients for recipe via scraper

### ISSUE THREAD

**Issue by jnymous** [TomBursch/kitchenowl#72]
### What's the feature 🧐

First off, thanks for the great app!

Currently when importing/scraping a recipe from a website, you have to manually retype the ingredients + amounts.

E.g. for the following ingredient/measurement: "3 tablespoon lemon juice", you would have to click on the " + " and type "lemon juice, 3 tbsp".

It would be nice if the app could parse the ingredient/measurement data and automatically fill the info, or make it an option via a checkbox "auto-import all".

**Comment by B4rc1** [comment]
Related: #80
