### ISSUE TITLE
Offline mode broken

### ISSUE THREAD

**Issue by irishrain** [TomBursch/kitchenowl#79]
I was just shopping in a store with bad reception at the back. Suddenly the whole shopping list vanished. It only returned when I went to the front of the store, forgetting my sort mode.
This can also be triggered by forced offline mode.
![Screenshot_20221027-181241](https://user-images.githubusercontent.com/74204581/198343314-1d9c1be6-8c8a-4bfd-8b07-94bb68b9f799.png)

**Comment by TomBursch** [comment]
Thanks for the issue. I have an idea where this is coming from. Most likely the health check passes (i.e. the app can reach the server) but getting data timeouts due to the bad connection and the cached data is only used if the health check fails.

**Comment by TomBursch** [comment]
Turns out that was only part of the issue. The offline mode should be way better with that PR.

**Comment by irishrain** [comment]
I tried the new version today. Much better - no completely black screen anymore. However, still some issues:
Some items just did not want to disappear, tapping, waiting, tapping again, nothing. Other items did disappear, but then reappeared some minutes later. Maybe you can work on offline mode some more?

**Comment by TomBursch** [comment]
Thanks for letting me know! Will look into it and yes there is definitely some work still needed. 
Did you refresh after the items reappeared? The refreshing of items and uploading the changes you made (i.e. the removal) happens at the same time right now, so sometimes the server returns items just milliseconds before they are deleted.

**Comment by irishrain** [comment]
I did not actively refresh (as in pulling down), but I turned my screen on and off several times, so it might have been auto refresh.
Maybe you could think about offline mode together with #92 , I have the feeling that there might be some possibility to kill two birds with one stone.

**Comment by irishrain** [comment]
Hi @TomBursch , sorry to bother you again with this. I went shopping again today, and after spending some time in the corner of the store without a signal, the shopping list vanished again, looking exactly as in the original screenshot. There must be another bug somewhere.
Is there a way to provide logs to help you understand what's going on?

**Comment by TomBursch** [comment]
Hey, no worries always happy for feedback. Strange, that shouldn't happen anymore. Did you try to refresh?
No sadly not, there are some bugs still in the offline mode. But the ones I'm aware of shouldn't cause the empty shopping list.

**Comment by irishrain** [comment]
Another week, another shopping trip, a new KitchenOwl version to try, a new round of feedback about the offline mode!
Good news first: No vanished list!
But still not bug-free. I tried paying more attention to what happened when, it might not be exactly accurate though:
I ticked off some items when reception was good, then walked towards the back of the store. My phone still displayed a 5G connection, but with low signal strenght (so it might have been already unusable). I ticked off some more items. A bit later, when I unlocked my phone, some of the items I removed in the area with spotty connection reapeared, and offline mode was active. I ticked them off again and continued shopping, ticking off more items. I paid and went outside, when I unlocked the screen in the parking lot, Kitchenowl was still in offline mode. I dragged the list down to trigger a refresh. Offline mode went away, but all the items I ticked off reapeared. Remembering your comment from last time, I waited a few seconds and refreshed again, but no luck, the items stayed.

I hope this helps to make offline mode better usable, and therefore KitchenOwl even better than it already is!

**Comment by TomBursch** [comment]
Thanks again for the feedback!
> I ticked off some more items. A bit later, when I unlocked my phone, some of the items I removed in the area with spotty connection reapeared, and offline mode was active.

I think I know what the issue you experienced is. Will be fixed soon.

>  Remembering your comment from last time, I waited a few seconds and refreshed again, but no luck, the items stayed.

Hmm that is really strange. Maybe on your next trip you could force the app into offline mode (under the profile tab) and then sync everything after your trip when the signal is better.

**Comment by irishrain** [comment]
Today offline mode worked quite well while I was in the shop (not forced, just went offline automatically when reception dropped). However, I had trouble getting out of offline mode. I was ten minutes out of the store when I looked at my phone again. Kitchenowl was still in offline mode. I tried pulling the shopping list down to refresh, no luck. After waiting some more I closed the app and restarted it: I was greeted with the log-in dialogue, and after logging in all items I had ticked off before reapeared. 

I think offline mode is quite close to working reliably, maybe this is my last comment on this issue :)

**Comment by TomBursch** [comment]
@irishrain Thanks again for the helpful information! I'll see if I can find some more bugs based on the description.

But again, really strange behavior as you should only ever be logged out if an authentication error happened (even through restarts).
You already did the same thing I would have done (pull to refresh/switching tabs) sometimes enabling/disabling forced offline mode helps too.
