### ISSUE TITLE
Feature request: Amount of Items in Grocery list/Recipes

### ISSUE THREAD

**Issue by B4rc1** [TomBursch/kitchenowl#80]
### What's the feature 🧐

Add the Option to add an amount to Ingredients you need in recipes and display these on the grocery list, so you know how much you need to buy when in the store. This is especially useful when trying out a new recipe as you could just check your grocery list and don't have to open the recipe everytime and read in the description of the recipe how much you actually need.

### Extra information and references

This is my current setup in Notion that has this feature:
Recipe view:
![grafik](https://user-images.githubusercontent.com/10383737/198875285-9d280d52-bbd0-474f-9609-b989e31ca844.png)

Shopping List view:
![grafik](https://user-images.githubusercontent.com/10383737/198875308-8284d136-bc7c-43c9-9252-5cbe0fab6b53.png)

**Comment by TomBursch** [comment]
You can already do that, see here https://tombursch.github.io/kitchenowl/tips-and-tricks/ for how. Or long press on an item while editing a recipe to change its description/amount. With the new yields feature the amount can also be dynamically adjusted based on the requested yields.

**Comment by B4rc1** [comment]
This is exactly what I want.

One Problem I have tho is that if two recipes require the same ingredient, just different amounts, it is not displayed correctly:
I have two recipes, one requiring 600g of "Blattspinat", another on requiring 200g of "Blattspinat":

![grafik](https://user-images.githubusercontent.com/10383737/198876459-9ecbcb86-b370-4114-8d23-dba36620fcae.png)

What I would expect would either be 800g of Blattspinat (the dream, but hard because as of right now the description is an arbitrary string) or "200g, 600g", just concatenating the description. 

Even if I long press on the Item, the ellipsis does not get removed:
![grafik](https://user-images.githubusercontent.com/10383737/198876528-1e2d778a-aa40-463f-a7d6-d8c2992fb0e7.png)

**Comment by TomBursch** [comment]
You're right. I need to change the behavior a bit. If the recipe is also on the meal planner that recipe is shown first including the item's description when long pressing an item in the shopping list. That's why I just server side shortened the string a bit. I didn't think about what happens if somebody does not use the meal planner. And now with recipe yields this meal plan linking won't work anymore either.

**Comment by TomBursch** [comment]
Okay I looked through this again and wanted to fix it but it already works as expected? When I add the same items for different recipes it concatenates them correctly. The `...` is only ever added if one recipe doesn't have a description for that item so you know that you have to buy it more than whatever amount is listed in the items description.

**Comment by Radoom** [comment]
Though closed and basically possible via the comments field, I'd also like a dedicated quantity and unit-of-packing (kg, l, pcs, packs, bags, pallets...) field per Item. 

We're not using the meal planner nor the recipe functionality at all. Likely will never do, as recipes need to be (for the WAF) linked to our beloved food processing super machine (Bosch "cook it"), so not managing recipes outside that universe. 

Shopping list for is "old school", totally detached from meal plan, recipe books etc.: go through what we have and need, (re)add to list, set quantity (or rather have same as usual, i.e. use last value normally). 

Would keep the "Description" field for real text / comments like "but not from store X, tastes crap there!"

Side note: To save screen space on mobile devices, in list view, it would be good to show the quantity / units field (if ever implemented) on the same line as the item label itself (if label  isn't too long on screen). This could also be applied now already, even without dedicated fields, e.g. by a rule like 
- "if len(description) < 10" or so. Reasoning: If I'd have e.g "5 L" or "1200 gr" in there only, it's the amount/unit. If it's >10, likely it's text with add. info on the item. 
- Alternative approach might be: "if first char is a digit" => starts with a number => most likely qty and packing maybe.

**Comment by Radoom** [comment]
> You can already do that, see here https://tombursch.github.io/kitchenowl/tips-and-tricks/ for how. 

Sidenote: Tips-**and**-Tricks == 404; it (now?) is [Tips & Tricks](https://docs.kitchenowl.org/Tips-%26-Tricks/)
