### ISSUE TITLE
Feature request: Multiple shopping lists

### ISSUE THREAD

**Issue by teemue** [TomBursch/kitchenowl#82]
### What's the feature 🧐

To extend possibilities this app could offer, multiple shopping lists and optional sharing between users would be a prizerunner :-) Like non-FOSS Bring!-app does.

**Comment by TomBursch** [comment]
Thanks for the issue! I really want to do this as some but I think we need to start a discussion about this as there are some open questions (for me at least) as to what would be the best way to implement this (are recipes/expenses shared between users/shopping lists and so on). This will also take some time as this will likely be a major change to the backend.

**Comment by inos-github** [comment]
Is there a possibility to make the shoppinglists rearrangeable in the UI?
