### ISSUE TITLE
Bring! integration?

### ISSUE THREAD

**Issue by ulimanaio** [TomBursch/kitchenowl#86]
### What's the feature 🧐

Hi, 
I would like to use kitchenowl as my recipe manager and Bring! as my shopping list.
There is a widget which can be integrated on the site:
![image](https://user-images.githubusercontent.com/95037770/199542630-63206246-82d1-49e2-81ed-2b41b4f78a1c.png)

As far as I understand recipies need to follow "Schema.org" or JSON-LD.
Here is their developer site:
https://www.getbring.com/en/integration-check
Widget Integration:
https://sites.google.com/getbring.com/bring-import-dev-guide/web-to-app-integration

Thank you very much

**Comment by TomBursch** [comment]
I think that integration only allows for adding the recipe to bring! not the items directly.
And although this seems rather easy I don't think this kind of integration is in the spirit of this project. If you miss features from the shopping list compared to bring I would much rather work on adding those than to make it compatible with bring.
