### ISSUE TITLE
Bug: Import of Recipe failed

### ISSUE THREAD

**Issue by TheBToby** [TomBursch/kitchenowl#87]
### Is this urgent?

Yes

### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

0.3.4

### What's the problem 🤔

I set up KichenOwl as a docker stack in Portainer 2.16.0 on my Synology NAS. Stack deployment worked with no issue and I can access the KichenOwl front-end through reverse proxy. But the import of recipes fails whatever URL I try. The only hint I got was in the log file of the kitchenowl-back-1 container (see below)

### Share your logs

```log
[2022-11-05 12:21:03,205] ERROR in config: Object of type method is not JSON serializable
ERROR:app.config:Object of type method is not JSON serializable
[pid: 25|app: 0|req: 15/49] 172.31.0.1 () {64 vars in 1506 bytes} [Sat Nov  5 12:21:01 2022] GET /api/recipe/scrape?url=https://www.chefkoch.de/rezepte/660551167895456/Hamburger-de-luxe.html => generated 35 bytes in 1256 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
```

### Share your configuration

```yml
version: "3"
services:
    front:
        image: tombursch/kitchenowl-web:latest
        ports:
        - 7180:80
        depends_on:
        - back
        networks:
        - default
    back:
        image: tombursch/kitchenowl:latest
        restart: unless-stopped
        networks:
        - default
        environment:
        - JWT_SECRET_KEY=********************************
        volumes:
        - /volume1/docker/kitchenowl:/data

volumes:
    kitchenowl_data:

networks:
    default:
```

**Comment by alongwhile** [comment]
I'm having the same issue. Not sure what changed with my configuration--possibly the update to 0.3.4?  Was working previously with older version, but, I've also been playing around with security headers (as noted in my other posted issue)--I was thinking maybe the security headers caused the problem, but i tried disabling them altogether today and it hasnt helped.  Seeing this post tells me its obviously not just my implementation causing a problem.  Guessing something broke during the 0.3.4 update...

My setup is docker on a 64bit pi, exposed via traefik.

```
ERROR:app.config:Object of type method is not JSON serializable
[pid: 24|app: 0|req: 134/252] 172.18.0.3 () {62 vars in 1420 bytes} [Sat Nov  5 15:41:16 2022] GET /api/recipe/scrape?url=https://www.yummly.com/recipe/Karam-Gavvalu-Recipe-_-Krishna-Jayanthi-Recipes-_-Janmashtami-Recipes-1769441?prm-v1 => generated 35 bytes in 1443 msecs (HTTP/1.1 500) 9 headers in 429 bytes (1 switches on core 0)
```

**Comment by eglia** [comment]
I'm still getting errors in most recipe imports in the latest build:
```ERROR:app.config:recipe-scrapers exception: Cooktime information not found in SchemaOrg```
The exception comes from [here](https://github.com/hhursev/recipe-scrapers/blob/main/recipe_scrapers/_schemaorg.py#L124). It seems that `SchemaOrgException` needs to be catched as well.

**Comment by TomBursch** [comment]
@eglia Thanks for the info! Should be fixed now.

**Comment by audas** [comment]
Just deployed latest version as docker container and it fails on every website. Is there something extra we need to add in the compose file? Do we need to install extra python?
