### ISSUE TITLE
Bug: Imported recipes do not have preview images due to CORS issues

### ISSUE THREAD

**Issue by beatbrot** [TomBursch/kitchenowl#93]
### Is this urgent?

No

### What parts are affected

Frontend

### What are the Server/Client versions of KitchenOwl

0.3.5

### What's the problem 🤔

When importing a recipe from chefkoch.de, the image is curretly imported and stored as URL in the database. Unfortunately, the image is not visible on the WebUI due to the CORS error `CORS Missing Allow Origin`.

Possible solutions:

- Proxy requests via backend 
- Store preview images in backend on import

### Share your logs

```log
None
```

### Share your configuration

```yml
Not relevant.
```

**Comment by TomBursch** [comment]
Thanks for the issue. I'm aware of this, I think the best option is to just download the image to the server
